steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'backend/Dockerfile', '-t', 'gcr.io/mdm-generator/mdm-backend:latest', '.']
images: ['gcr.io/mdm-generator/mdm-backend:latest']
