import { z } from 'zod'

// ============================================================================
// Character limits for each section
// ============================================================================
export const SECTION1_MAX_CHARS = 4000
export const SECTION2_MAX_CHARS = 3000
export const SECTION3_MAX_CHARS = 2500

// ============================================================================
// Request Schemas
// ============================================================================

/**
 * Section 1: Initial Evaluation
 * Patient presentation, HPI, exam findings, risk factors, initial impression
 */
export const Section1RequestSchema = z.object({
  encounterId: z.string().min(1),
  content: z.string().min(1).max(SECTION1_MAX_CHARS),
  userIdToken: z.string().min(10),
})

export type Section1Request = z.infer<typeof Section1RequestSchema>

/**
 * Section 2: Workup & Results
 * Labs, imaging, EKG, clinical decision rules, working diagnosis
 */
export const Section2RequestSchema = z.object({
  encounterId: z.string().min(1),
  content: z.string().min(1).max(SECTION2_MAX_CHARS),
  workingDiagnosis: z.string().optional(),
  userIdToken: z.string().min(10),
})

export type Section2Request = z.infer<typeof Section2RequestSchema>

/**
 * Section 3: Treatment & Disposition (Finalize)
 * Medications, procedures, response to treatment, consultations, disposition
 */
export const FinalizeRequestSchema = z.object({
  encounterId: z.string().min(1),
  content: z.string().min(1).max(SECTION3_MAX_CHARS),
  userIdToken: z.string().min(10),
})

export type FinalizeRequest = z.infer<typeof FinalizeRequestSchema>

// ============================================================================
// Response Schemas
// ============================================================================

/**
 * Individual differential diagnosis item
 * Generated by Section 1 processing
 */
export const DifferentialItemSchema = z.object({
  diagnosis: z.string(),
  urgency: z.enum(['emergent', 'urgent', 'routine']),
  reasoning: z.string(),
})

export type DifferentialItem = z.infer<typeof DifferentialItemSchema>

/**
 * Section 1 Response: Worst-first differential diagnosis list
 */
export const Section1ResponseSchema = z.object({
  differential: z.array(DifferentialItemSchema),
  submissionCount: z.number().int().min(0).max(2),
  isLocked: z.boolean(),
  quotaRemaining: z.number().int().min(0),
})

export type Section1Response = z.infer<typeof Section1ResponseSchema>

/**
 * MDM Preview structure
 * Accumulated from Section 1 + Section 2
 */
export const MdmPreviewSchema = z.object({
  problems: z.union([z.string(), z.array(z.string())]),
  differential: z.union([z.string(), z.array(z.string())]),
  dataReviewed: z.union([z.string(), z.array(z.string())]),
  reasoning: z.string(),
})

export type MdmPreview = z.infer<typeof MdmPreviewSchema>

/**
 * Section 2 Response: MDM preview with accumulated context
 */
export const Section2ResponseSchema = z.object({
  mdmPreview: MdmPreviewSchema,
  submissionCount: z.number().int().min(0).max(2),
  isLocked: z.boolean(),
})

export type Section2Response = z.infer<typeof Section2ResponseSchema>

/**
 * Final MDM structure
 * Complete MDM ready for copy-paste into EHR
 */
export const FinalMdmSchema = z.object({
  text: z.string(),
  json: z.object({
    problems: z.union([z.string(), z.array(z.string())]),
    differential: z.union([z.string(), z.array(z.string())]),
    dataReviewed: z.union([z.string(), z.array(z.string())]),
    reasoning: z.string(),
    risk: z.union([z.string(), z.array(z.string())]),
    disposition: z.string(),
    complexityLevel: z.enum(['low', 'moderate', 'high']).optional(),
  }),
})

export type FinalMdm = z.infer<typeof FinalMdmSchema>

/**
 * Finalize Response: Complete MDM and quota info
 */
export const FinalizeResponseSchema = z.object({
  finalMdm: FinalMdmSchema,
  quotaRemaining: z.number().int().min(0),
})

export type FinalizeResponse = z.infer<typeof FinalizeResponseSchema>

// ============================================================================
// Firestore Document Schemas (for validation)
// ============================================================================

/**
 * Section status in Firestore
 */
export const SectionStatusSchema = z.enum(['pending', 'in_progress', 'completed'])

export type SectionStatus = z.infer<typeof SectionStatusSchema>

/**
 * Encounter status in Firestore
 */
export const EncounterStatusSchema = z.enum([
  'draft',
  'section1_done',
  'section2_done',
  'finalized',
  'archived',
])

export type EncounterStatus = z.infer<typeof EncounterStatusSchema>

/**
 * Section data structure for Firestore
 */
export const SectionDataSchema = z.object({
  content: z.string().default(''),
  status: SectionStatusSchema.default('pending'),
  submissionCount: z.number().int().min(0).max(2).default(0),
  llmResponse: z.any().nullable().default(null),
  lastUpdated: z.any().nullable().default(null), // Firestore Timestamp
})

export type SectionData = z.infer<typeof SectionDataSchema>

/**
 * Full encounter document schema for Firestore
 */
export const EncounterDocumentSchema = z.object({
  userId: z.string(),
  roomNumber: z.string(),
  chiefComplaint: z.string(),
  status: EncounterStatusSchema.default('draft'),
  quotaCounted: z.boolean().default(false),
  section1: SectionDataSchema.default({}),
  section2: SectionDataSchema.default({}),
  section3: SectionDataSchema.default({}),
  createdAt: z.any(), // Firestore Timestamp
  updatedAt: z.any(), // Firestore Timestamp
  shiftStartedAt: z.any(), // Firestore Timestamp
})

export type EncounterDocument = z.infer<typeof EncounterDocumentSchema>
