import type { CdrSeed } from './types'

export const batch6CritPedsCdrs: CdrSeed[] = [

  // DISPOSITION / RISK STRATIFICATION — APACHE II
  {
    id: 'apache_ii',
    name: 'APACHE II',
    fullName: 'APACHE II (Acute Physiology and Chronic Health Evaluation II)',
    category: 'DISPOSITION / RISK STRATIFICATION',
    application: 'ICU mortality prediction; calculated within first 24 hours of ICU admission using worst physiological values. Score >34 associated with >85% mortality.',
    applicableChiefComplaints: ['ICU_admission', 'critical_illness', 'sepsis', 'multi_organ_failure'],
    keywords: ['APACHE II', 'ICU mortality', 'critical illness', 'severity of illness', 'prognosis', 'acute physiology', 'mortality prediction'],
    requiredTests: ['vbg_abg', 'bmp', 'cbc'],
    components: [
      // Acute Physiology Score (APS) — 12 variables, each 0–4 points
      {
        id: 'temperature',
        label: 'Rectal Temperature (°C)',
        type: 'select',
        source: 'section1',
        options: [
          { label: '≥41 or <29.9', value: 4 },
          { label: '39–40.9', value: 3 },
          { label: '38.5–38.9', value: 1 },
          { label: '36–38.4 (normal)', value: 0 },
          { label: '34–35.9', value: 1 },
          { label: '32–33.9', value: 2 },
          { label: '30–31.9', value: 3 },
        ],
      },
      {
        id: 'mean_arterial_pressure',
        label: 'Mean Arterial Pressure (mmHg)',
        type: 'select',
        source: 'section1',
        options: [
          { label: '≥160 or <49', value: 4 },
          { label: '130–159', value: 3 },
          { label: '110–129', value: 2 },
          { label: '70–109 (normal)', value: 0 },
          { label: '50–69', value: 2 },
        ],
      },
      {
        id: 'heart_rate',
        label: 'Heart Rate (bpm)',
        type: 'select',
        source: 'section1',
        options: [
          { label: '≥180 or <39', value: 4 },
          { label: '140–179', value: 3 },
          { label: '110–139', value: 2 },
          { label: '70–109 (normal)', value: 0 },
          { label: '55–69', value: 2 },
          { label: '40–54', value: 3 },
        ],
      },
      {
        id: 'respiratory_rate',
        label: 'Respiratory Rate (breaths/min)',
        type: 'select',
        source: 'section1',
        options: [
          { label: '≥50 or <6', value: 4 },
          { label: '35–49', value: 3 },
          { label: '25–34', value: 1 },
          { label: '12–24 (normal)', value: 0 },
          { label: '10–11', value: 1 },
          { label: '6–9', value: 2 },
        ],
      },
      {
        id: 'oxygenation',
        label: 'Oxygenation: A-aDO₂ or PaO₂',
        type: 'select',
        source: 'section2',
        autoPopulateFrom: 'test_result',
        options: [
          { label: 'FiO₂ ≥0.5: A-aDO₂ ≥500', value: 4 },
          { label: 'FiO₂ ≥0.5: A-aDO₂ 350–499', value: 3 },
          { label: 'FiO₂ ≥0.5: A-aDO₂ 200–349', value: 2 },
          { label: 'FiO₂ ≥0.5: A-aDO₂ <200 (normal)', value: 0 },
          { label: 'FiO₂ <0.5: PaO₂ ≥70 (normal)', value: 0 },
          { label: 'FiO₂ <0.5: PaO₂ 61–70', value: 1 },
          { label: 'FiO₂ <0.5: PaO₂ 55–60', value: 3 },
          { label: 'FiO₂ <0.5: PaO₂ <55', value: 4 },
        ],
      },
      {
        id: 'arterial_ph',
        label: 'Arterial pH',
        type: 'select',
        source: 'section2',
        autoPopulateFrom: 'test_result',
        options: [
          { label: '≥7.70 or <7.15', value: 4 },
          { label: '7.60–7.69', value: 3 },
          { label: '7.50–7.59', value: 1 },
          { label: '7.33–7.49 (normal)', value: 0 },
          { label: '7.25–7.32', value: 2 },
          { label: '7.15–7.24', value: 3 },
        ],
      },
      {
        id: 'serum_sodium',
        label: 'Serum Sodium (mEq/L)',
        type: 'select',
        source: 'section2',
        autoPopulateFrom: 'test_result',
        options: [
          { label: '≥180 or <110', value: 4 },
          { label: '160–179', value: 3 },
          { label: '155–159', value: 2 },
          { label: '150–154', value: 1 },
          { label: '130–149 (normal)', value: 0 },
          { label: '120–129', value: 2 },
          { label: '111–119', value: 3 },
        ],
      },
      {
        id: 'serum_potassium',
        label: 'Serum Potassium (mEq/L)',
        type: 'select',
        source: 'section2',
        autoPopulateFrom: 'test_result',
        options: [
          { label: '≥7.0 or <2.5', value: 4 },
          { label: '6.0–6.9', value: 3 },
          { label: '5.5–5.9', value: 1 },
          { label: '3.5–5.4 (normal)', value: 0 },
          { label: '3.0–3.4', value: 1 },
          { label: '2.5–2.9', value: 2 },
        ],
      },
      {
        id: 'serum_creatinine',
        label: 'Serum Creatinine (mg/dL) — double if acute renal failure',
        type: 'select',
        source: 'section2',
        autoPopulateFrom: 'test_result',
        options: [
          { label: '≥3.5 (×2 if ARF = 4 pts)', value: 4 },
          { label: '2.0–3.4 (×2 if ARF = 3 pts)', value: 2 },
          { label: '1.5–1.9 (×2 if ARF = 2 pts)', value: 2 },
          { label: '0.6–1.4 (normal)', value: 0 },
          { label: '<0.6', value: 2 },
        ],
      },
      {
        id: 'hematocrit',
        label: 'Hematocrit (%)',
        type: 'select',
        source: 'section2',
        autoPopulateFrom: 'test_result',
        options: [
          { label: '≥60', value: 4 },
          { label: '50–59.9', value: 2 },
          { label: '46–49.9', value: 1 },
          { label: '30–45.9 (normal)', value: 0 },
          { label: '20–29.9', value: 2 },
          { label: '<20', value: 4 },
        ],
      },
      {
        id: 'wbc',
        label: 'WBC (×10³/µL)',
        type: 'select',
        source: 'section2',
        autoPopulateFrom: 'test_result',
        options: [
          { label: '≥40', value: 4 },
          { label: '20–39.9', value: 2 },
          { label: '15–19.9', value: 1 },
          { label: '3–14.9 (normal)', value: 0 },
          { label: '1–2.9', value: 2 },
          { label: '<1', value: 4 },
        ],
      },
      {
        id: 'gcs_apache',
        label: 'GCS Points (15 minus actual GCS)',
        type: 'select',
        source: 'section1',
        autoPopulateFrom: 'narrative_analysis',
        options: [
          { label: 'GCS 15 (normal) → 0 pts', value: 0 },
          { label: 'GCS 13–14 → 1–2 pts', value: 1 },
          { label: 'GCS 10–12 → 3–5 pts', value: 3 },
          { label: 'GCS 7–9 → 6–8 pts', value: 6 },
          { label: 'GCS 4–6 → 9–11 pts', value: 9 },
          { label: 'GCS 3 → 12 pts', value: 12 },
        ],
      },
      // Age points
      {
        id: 'age_points',
        label: 'Age',
        type: 'select',
        source: 'section1',
        autoPopulateFrom: 'narrative_analysis',
        options: [
          { label: '<44 years', value: 0 },
          { label: '45–54 years', value: 2 },
          { label: '55–64 years', value: 3 },
          { label: '65–74 years', value: 5 },
          { label: '≥75 years', value: 6 },
        ],
      },
      // Chronic Health Points
      {
        id: 'chronic_health',
        label: 'Chronic Health (severe organ insufficiency or immunocompromised)',
        type: 'select',
        source: 'section1',
        autoPopulateFrom: 'narrative_analysis',
        options: [
          { label: 'None', value: 0 },
          { label: 'Elective postop admission with organ insufficiency', value: 2 },
          { label: 'Emergency postop or non-operative with organ insufficiency', value: 5 },
        ],
      },
    ],
    scoring: {
      method: 'sum',
      ranges: [
        { min: 0, max: 4, risk: 'Low', interpretation: 'Score 0–4: ~4% predicted ICU mortality' },
        { min: 5, max: 9, risk: 'Low-Moderate', interpretation: 'Score 5–9: ~8% predicted ICU mortality' },
        { min: 10, max: 14, risk: 'Moderate', interpretation: 'Score 10–14: ~15% predicted ICU mortality' },
        { min: 15, max: 19, risk: 'Moderate-High', interpretation: 'Score 15–19: ~25% predicted ICU mortality' },
        { min: 20, max: 24, risk: 'High', interpretation: 'Score 20–24: ~40% predicted ICU mortality' },
        { min: 25, max: 29, risk: 'High', interpretation: 'Score 25–29: ~55% predicted ICU mortality' },
        { min: 30, max: 34, risk: 'Very High', interpretation: 'Score 30–34: ~75% predicted ICU mortality' },
        { min: 35, max: 71, risk: 'Critical', interpretation: 'Score >34: >85% predicted ICU mortality' },
      ],
    },
    suggestedTreatments: {
      Critical: ['icu_admission', 'vasopressors', 'mechanical_ventilation', 'palliative_goals_of_care'],
      'Very High': ['icu_admission', 'vasopressors', 'invasive_monitoring'],
      High: ['icu_admission', 'aggressive_resuscitation', 'specialist_consult'],
      'Moderate-High': ['icu_admission', 'aggressive_monitoring', 'specialist_consult'],
      Moderate: ['icu_or_step_down', 'close_monitoring', 'specialist_consult'],
      'Low-Moderate': ['step_down_unit', 'close_monitoring', 'reassess_in_24h'],
      Low: ['routine_icu_monitoring', 'reassess_per_protocol'],
    },
  },

  // DISPOSITION / RISK STRATIFICATION — NEWS2
  {
    id: 'news2',
    name: 'NEWS2',
    fullName: 'NEWS2 (National Early Warning Score 2)',
    category: 'DISPOSITION / RISK STRATIFICATION',
    application: 'Detects clinical deterioration and identifies need for escalation of care. Used for inpatient monitoring and ED triage. Score ≥7 warrants emergency response and critical care assessment.',
    applicableChiefComplaints: ['clinical_deterioration', 'inpatient_monitoring', 'sepsis', 'respiratory_failure'],
    keywords: ['NEWS2', 'National Early Warning Score', 'deterioration', 'inpatient', 'escalation', 'sepsis', 'respiratory rate', 'SpO2', 'COPD'],
    components: [
      {
        id: 'respiratory_rate',
        label: 'Respiratory Rate (breaths/min)',
        type: 'select',
        source: 'section1',
        options: [
          { label: '≤8', value: 3 },
          { label: '9–11', value: 1 },
          { label: '12–20 (normal)', value: 0 },
          { label: '21–24', value: 2 },
          { label: '≥25', value: 3 },
        ],
      },
      {
        id: 'spo2_scale1',
        label: 'SpO₂ Scale 1 (non-hypercapnic — most patients)',
        type: 'select',
        source: 'section1',
        options: [
          { label: '≤91%', value: 3 },
          { label: '92–93%', value: 2 },
          { label: '94–95%', value: 1 },
          { label: '≥96% (normal)', value: 0 },
        ],
      },
      {
        id: 'spo2_scale2',
        label: 'SpO₂ Scale 2 (hypercapnic/COPD target 88–92%) — use only if confirmed hypercapnic',
        type: 'select',
        source: 'section1',
        options: [
          { label: 'Not applicable (Scale 1 used)', value: 0 },
          { label: '≤83%', value: 3 },
          { label: '84–85%', value: 2 },
          { label: '86–87%', value: 1 },
          { label: '88–92% (target range)', value: 0 },
          { label: '93–94% on air', value: 1 },
          { label: '95–96% on air', value: 2 },
          { label: '≥97% on air', value: 3 },
        ],
      },
      {
        id: 'supplemental_oxygen',
        label: 'Supplemental Oxygen',
        type: 'boolean',
        value: 2,
        source: 'section1',
      },
      {
        id: 'systolic_bp',
        label: 'Systolic Blood Pressure (mmHg)',
        type: 'select',
        source: 'section1',
        options: [
          { label: '≤90', value: 3 },
          { label: '91–100', value: 2 },
          { label: '101–110', value: 1 },
          { label: '111–219 (normal)', value: 0 },
          { label: '≥220', value: 3 },
        ],
      },
      {
        id: 'heart_rate',
        label: 'Heart Rate (bpm)',
        type: 'select',
        source: 'section1',
        options: [
          { label: '≤40', value: 3 },
          { label: '41–50', value: 1 },
          { label: '51–90 (normal)', value: 0 },
          { label: '91–110', value: 1 },
          { label: '111–130', value: 2 },
          { label: '≥131', value: 3 },
        ],
      },
      {
        id: 'consciousness',
        label: 'Consciousness (ACVPU)',
        type: 'select',
        source: 'section1',
        autoPopulateFrom: 'narrative_analysis',
        options: [
          { label: 'Alert (normal)', value: 0 },
          { label: 'Confusion (new)', value: 3 },
          { label: 'Voice (responds to voice)', value: 3 },
          { label: 'Pain (responds to pain)', value: 3 },
          { label: 'Unresponsive', value: 3 },
        ],
      },
      {
        id: 'temperature',
        label: 'Temperature (°C)',
        type: 'select',
        source: 'section1',
        options: [
          { label: '≤35.0', value: 3 },
          { label: '35.1–36.0', value: 1 },
          { label: '36.1–38.0 (normal)', value: 0 },
          { label: '38.1–39.0', value: 1 },
          { label: '≥39.1', value: 2 },
        ],
      },
    ],
    scoring: {
      method: 'sum',
      ranges: [
        { min: 0, max: 4, risk: 'Low', interpretation: 'Score 0–4: Low clinical risk; minimum 12-hourly monitoring recommended' },
        { min: 5, max: 6, risk: 'Medium', interpretation: 'Score 5–6: Medium risk; urgent response within 30–60 min; consider escalation to higher monitoring level' },
        { min: 7, max: 23, risk: 'High', interpretation: 'Score ≥7: High risk; emergency response; continuous monitoring; critical care assessment required' },
      ],
    },
    suggestedTreatments: {
      High: ['emergency_response_team', 'continuous_monitoring', 'critical_care_consult', 'sepsis_bundle'],
      Medium: ['urgent_physician_review', 'increased_monitoring_frequency', 'consider_escalation'],
      Low: ['routine_monitoring', 'reassess_per_protocol'],
    },
  },

  // DISPOSITION / RISK STRATIFICATION — Glasgow Coma Scale (GCS)
  {
    id: 'gcs',
    name: 'GCS',
    fullName: 'Glasgow Coma Scale (GCS)',
    category: 'DISPOSITION / RISK STRATIFICATION',
    application: 'Standardized assessment of level of consciousness. GCS ≤8 generally indicates need for airway protection. Report as total score and component subscores (E+V+M).',
    applicableChiefComplaints: ['altered_mental_status', 'head_trauma', 'traumatic_brain_injury', 'unresponsive', 'coma', 'seizure'],
    keywords: ['GCS', 'Glasgow Coma Scale', 'level of consciousness', 'LOC', 'TBI', 'head injury', 'eye opening', 'verbal', 'motor', 'intubation threshold'],
    components: [
      {
        id: 'eye_opening',
        label: 'Eye Opening (E)',
        type: 'select',
        source: 'section1',
        autoPopulateFrom: 'narrative_analysis',
        options: [
          { label: 'Spontaneous (E4)', value: 4 },
          { label: 'To voice (E3)', value: 3 },
          { label: 'To pain (E2)', value: 2 },
          { label: 'None (E1)', value: 1 },
        ],
      },
      {
        id: 'verbal_response',
        label: 'Verbal Response (V)',
        type: 'select',
        source: 'section1',
        autoPopulateFrom: 'narrative_analysis',
        options: [
          { label: 'Oriented (V5)', value: 5 },
          { label: 'Confused (V4)', value: 4 },
          { label: 'Inappropriate words (V3)', value: 3 },
          { label: 'Incomprehensible sounds (V2)', value: 2 },
          { label: 'None (V1)', value: 1 },
        ],
      },
      {
        id: 'motor_response',
        label: 'Motor Response (M)',
        type: 'select',
        source: 'section1',
        autoPopulateFrom: 'narrative_analysis',
        options: [
          { label: 'Obeys commands (M6)', value: 6 },
          { label: 'Localizes pain (M5)', value: 5 },
          { label: 'Withdraws to pain (M4)', value: 4 },
          { label: 'Abnormal flexion/Decorticate (M3)', value: 3 },
          { label: 'Extension/Decerebrate (M2)', value: 2 },
          { label: 'None (M1)', value: 1 },
        ],
      },
    ],
    scoring: {
      method: 'sum',
      ranges: [
        { min: 13, max: 15, risk: 'Mild', interpretation: 'GCS 13–15: Mild impairment; mild TBI if trauma present; monitor closely for deterioration' },
        { min: 9, max: 12, risk: 'Moderate', interpretation: 'GCS 9–12: Moderate brain injury; close monitoring; consider CT head; neurosurgery notification' },
        { min: 3, max: 8, risk: 'Severe', interpretation: 'GCS ≤8: Severe brain injury; airway protection generally indicated; emergent CT head; neurosurgery consult; ICU admission' },
      ],
    },
    suggestedTreatments: {
      Severe: ['airway_intubation', 'ct_head', 'neurosurgery_consult', 'icu_admission', 'icp_monitoring'],
      Moderate: ['ct_head', 'neurosurgery_notification', 'close_monitoring', 'avoid_sedation'],
      Mild: ['ct_head_if_indicated', 'observation', 'serial_neuro_checks'],
    },
  },

  // CRITICAL CARE & ICU — CAM-ICU
  {
    id: 'cam_icu',
    name: 'CAM-ICU',
    fullName: 'CAM-ICU (Confusion Assessment Method for ICU)',
    category: 'CRITICAL CARE & ICU',
    application: 'Detects delirium in ICU patients, including those who are mechanically ventilated. Requires RASS −3 to +4; patients at RASS −4 or −5 are too sedated to assess. Sensitivity 93–100%, specificity 89–100%.',
    applicableChiefComplaints: ['icu_delirium', 'altered_mental_status', 'agitation', 'confusion'],
    keywords: ['CAM-ICU', 'delirium', 'ICU delirium', 'confusion assessment method', 'inattention', 'mechanically ventilated', 'RASS', 'PICS'],
    components: [
      {
        id: 'rass',
        label: 'RASS (Richmond Agitation-Sedation Scale) — prerequisite',
        type: 'select',
        source: 'section1',
        options: [
          { label: 'RASS −4 or −5: Unarousable/deeply sedated — CAM-ICU cannot be performed', value: 0 },
          { label: 'RASS −3 to +4: Proceed with CAM-ICU assessment', value: 0 },
        ],
      },
      // Feature 1: Acute onset or fluctuating course
      {
        id: 'feature_1_acute_onset',
        label: 'Feature 1: Acute onset OR fluctuating mental status (from baseline)',
        type: 'boolean',
        value: 1,
        source: 'section1',
        autoPopulateFrom: 'narrative_analysis',
      },
      // Feature 2: Inattention (Letters Attention Test ≥2 errors OR picture recognition test)
      {
        id: 'feature_2_inattention',
        label: 'Feature 2: Inattention (ASE letters test ≥2 errors or picture recognition fails)',
        type: 'boolean',
        value: 1,
        source: 'section1',
      },
      // Feature 3: Altered level of consciousness (RASS ≠ 0)
      {
        id: 'feature_3_altered_loc',
        label: 'Feature 3: Altered level of consciousness (RASS ≠ 0 — any deviation from alert)',
        type: 'boolean',
        value: 1,
        source: 'section1',
      },
      // Feature 4: Disorganized thinking (logic questions + command test ≥2 errors)
      {
        id: 'feature_4_disorganized_thinking',
        label: 'Feature 4: Disorganized thinking (logic Qs + "hold up fingers" command ≥2 errors)',
        type: 'boolean',
        value: 1,
        source: 'section1',
      },
    ],
    scoring: {
      // CAM-ICU is positive when: Feature 1 + Feature 2 + (Feature 3 OR Feature 4)
      // Encoding as algorithm because it is not a simple sum
      method: 'algorithm',
      ranges: [
        { min: 0, max: 1, risk: 'Negative', interpretation: 'CAM-ICU negative: Criteria not met — delirium absent at this assessment; reassess q4–8h per protocol' },
        { min: 2, max: 4, risk: 'Positive', interpretation: 'CAM-ICU positive: Feature 1 + Feature 2 + Feature 3 or 4 → Delirium present; identify and treat precipitating factors (pain, sedation, environment); implement ABCDEF bundle; minimize deliriogenic medications' },
      ],
    },
    suggestedTreatments: {
      Positive: [
        'abcdef_bundle',
        'minimize_benzodiazepines',
        'reorientation_protocol',
        'early_mobility',
        'sleep_protocol',
        'pain_control_optimization',
        'antipsychotic_if_agitated_and_safe',
      ],
      Negative: ['continue_routine_monitoring', 'reassess_q4_8h_per_protocol'],
    },
  },

  // PEDIATRIC — Westley Croup Score
  {
    id: 'westley_croup',
    name: 'Westley Croup Score',
    fullName: 'Westley Croup Score',
    category: 'PEDIATRIC',
    application: 'Quantifies croup severity to guide treatment (dexamethasone, nebulized epinephrine). Score ≥12 indicates impending respiratory failure.',
    applicableChiefComplaints: ['croup', 'stridor', 'barking_cough', 'respiratory_distress', 'upper_airway_obstruction'],
    keywords: ['Westley', 'croup', 'laryngotracheobronchitis', 'stridor', 'dexamethasone', 'epinephrine', 'respiratory distress', 'barking cough'],
    components: [
      {
        id: 'stridor',
        label: 'Stridor',
        type: 'select',
        source: 'section1',
        autoPopulateFrom: 'narrative_analysis',
        options: [
          { label: 'None', value: 0 },
          { label: 'With agitation/activity only', value: 1 },
          { label: 'At rest', value: 2 },
        ],
      },
      {
        id: 'retractions',
        label: 'Retractions',
        type: 'select',
        source: 'section1',
        options: [
          { label: 'None', value: 0 },
          { label: 'Mild', value: 1 },
          { label: 'Moderate', value: 2 },
          { label: 'Severe', value: 3 },
        ],
      },
      {
        id: 'air_entry',
        label: 'Air Entry',
        type: 'select',
        source: 'section1',
        options: [
          { label: 'Normal', value: 0 },
          { label: 'Decreased', value: 1 },
          { label: 'Markedly decreased', value: 2 },
        ],
      },
      {
        id: 'cyanosis',
        label: 'Cyanosis',
        type: 'select',
        source: 'section1',
        options: [
          { label: 'None', value: 0 },
          { label: 'With agitation', value: 4 },
          { label: 'At rest', value: 5 },
        ],
      },
      {
        id: 'level_of_consciousness',
        label: 'Level of Consciousness',
        type: 'select',
        source: 'section1',
        autoPopulateFrom: 'narrative_analysis',
        options: [
          { label: 'Normal / easily arousable', value: 0 },
          { label: 'Decreased / difficult to arouse', value: 5 },
        ],
      },
    ],
    scoring: {
      method: 'sum',
      ranges: [
        { min: 0, max: 2, risk: 'Mild', interpretation: 'Score ≤2: Mild croup; treat with single dose dexamethasone 0.6 mg/kg PO/IM; discharge appropriate for most patients with close follow-up' },
        { min: 3, max: 5, risk: 'Moderate', interpretation: 'Score 3–5: Moderate croup; dexamethasone 0.6 mg/kg + consider nebulized racemic epinephrine (0.05 mL/kg of 2.25% solution); observe 2–4 hours post-epinephrine before discharge' },
        { min: 6, max: 11, risk: 'Severe', interpretation: 'Score 6–11: Severe croup; dexamethasone + nebulized epinephrine; hospital admission required; heliox if available and worsening' },
        { min: 12, max: 17, risk: 'Critical', interpretation: 'Score ≥12: Impending respiratory failure; prepare for intubation (smaller tube than expected); nebulized epinephrine + dexamethasone; emergent ENT/anesthesia backup; ICU admission' },
      ],
    },
    suggestedTreatments: {
      Critical: ['nebulized_racemic_epinephrine', 'dexamethasone_0.6mgkg', 'prepare_intubation', 'icu_admission', 'ent_consult'],
      Severe: ['nebulized_racemic_epinephrine', 'dexamethasone_0.6mgkg', 'admit_observation', 'continuous_monitoring'],
      Moderate: ['dexamethasone_0.6mgkg', 'nebulized_epinephrine_if_needed', 'observe_2_4h'],
      Mild: ['dexamethasone_0.6mgkg', 'discharge_instructions', 'return_precautions'],
    },
  },

  // PEDIATRIC — Gorelick Dehydration Scale
  {
    id: 'gorelick_dehydration',
    name: 'Gorelick Dehydration Scale',
    fullName: 'Gorelick Dehydration Scale',
    category: 'PEDIATRIC',
    application: 'Estimates degree of dehydration in children 1 month to 5 years. The 10-item scale (each item = 1 point) predicts ≥5% dehydration with score ≥3; ≥10% dehydration with score ≥7.',
    applicableChiefComplaints: ['dehydration', 'vomiting', 'diarrhea', 'gastroenteritis', 'poor_oral_intake'],
    keywords: ['Gorelick', 'dehydration', 'pediatric', 'gastroenteritis', 'vomiting', 'diarrhea', 'fluid deficit', 'rehydration'],
    components: [
      {
        id: 'abnormal_capillary_refill',
        label: 'Capillary refill time >2 seconds',
        type: 'boolean',
        value: 1,
        source: 'section1',
      },
      {
        id: 'abnormal_skin_turgor',
        label: 'Abnormal skin turgor (tenting)',
        type: 'boolean',
        value: 1,
        source: 'section1',
      },
      {
        id: 'abnormal_respiratory_pattern',
        label: 'Abnormal respiratory pattern (deep/rapid)',
        type: 'boolean',
        value: 1,
        source: 'section1',
      },
      {
        id: 'abnormal_systolic_bp',
        label: 'Abnormal systolic BP (low for age)',
        type: 'boolean',
        value: 1,
        source: 'section1',
      },
      {
        id: 'no_tears',
        label: 'Absent tears',
        type: 'boolean',
        value: 1,
        source: 'section1',
      },
      {
        id: 'dry_mucous_membranes',
        label: 'Dry mucous membranes',
        type: 'boolean',
        value: 1,
        source: 'section1',
      },
      {
        id: 'sunken_eyes',
        label: 'Sunken eyes (by physician observation)',
        type: 'boolean',
        value: 1,
        source: 'section1',
      },
      {
        id: 'sunken_fontanel',
        label: 'Sunken anterior fontanel (infants)',
        type: 'boolean',
        value: 1,
        source: 'section1',
      },
      {
        id: 'tachycardia',
        label: 'Tachycardia (HR >150 bpm in infants; >130 in toddlers)',
        type: 'boolean',
        value: 1,
        source: 'section1',
      },
      {
        id: 'decreased_urine_output',
        label: 'Decreased urine output (by history)',
        type: 'boolean',
        value: 1,
        source: 'section1',
        autoPopulateFrom: 'narrative_analysis',
      },
    ],
    scoring: {
      method: 'sum',
      ranges: [
        { min: 0, max: 0, risk: 'Minimal', interpretation: 'Score 0: <5% dehydration estimated; oral rehydration therapy; routine PO trial' },
        { min: 1, max: 2, risk: 'Mild', interpretation: 'Score 1–2: ~5% dehydration (~50 mL/kg deficit); oral rehydration therapy with ondansetron if vomiting; reassess hydration status' },
        { min: 3, max: 6, risk: 'Moderate', interpretation: 'Score 3–6: ~5–10% dehydration (~50–100 mL/kg deficit); consider IV fluid resuscitation (NS 10–20 mL/kg bolus); reassess frequently' },
        { min: 7, max: 10, risk: 'Severe', interpretation: 'Score ≥7: >10% dehydration (>100 mL/kg deficit); IV fluid resuscitation required; 20 mL/kg NS bolus and repeat as needed; consider admission; monitor electrolytes' },
      ],
    },
    suggestedTreatments: {
      Severe: ['iv_fluid_bolus_20mkg_ns', 'bmp', 'admission_consideration', 'continuous_monitoring'],
      Moderate: ['iv_fluids_or_aggressive_ort', 'ondansetron', 'electrolyte_check'],
      Mild: ['oral_rehydration_therapy', 'ondansetron_if_vomiting', 'discharge_with_instructions'],
      Minimal: ['oral_rehydration_therapy', 'discharge_instructions'],
    },
  },

  // PEDIATRIC — PEWS (Pediatric Early Warning Score)
  {
    id: 'pews',
    name: 'PEWS',
    fullName: 'PEWS (Pediatric Early Warning Score)',
    category: 'PEDIATRIC',
    application: 'Identifies pediatric inpatients at risk for clinical deterioration. Score ≥5 warrants immediate physician evaluation and consideration of PICU transfer. Validated in inpatient and ED settings.',
    applicableChiefComplaints: ['clinical_deterioration', 'respiratory_distress', 'altered_mental_status', 'shock'],
    keywords: ['PEWS', 'pediatric early warning score', 'deterioration', 'pediatric', 'inpatient', 'PICU', 'rapid response', 'escalation'],
    components: [
      {
        id: 'behavior',
        label: 'Behavior',
        type: 'select',
        source: 'section1',
        autoPopulateFrom: 'narrative_analysis',
        options: [
          { label: 'Playing/appropriate', value: 0 },
          { label: 'Sleeping', value: 1 },
          { label: 'Irritable', value: 2 },
          { label: 'Confused/reduced response to pain', value: 3 },
        ],
      },
      {
        id: 'cardiovascular',
        label: 'Cardiovascular',
        type: 'select',
        source: 'section1',
        options: [
          { label: 'Pink; CRT 1–2 sec', value: 0 },
          { label: 'Pale; CRT 3 sec', value: 1 },
          { label: 'Gray; CRT 4 sec; tachycardia ≥20 above normal', value: 2 },
          { label: 'Gray and mottled; CRT ≥5 sec; tachycardia ≥30 above normal OR bradycardia', value: 3 },
        ],
      },
      {
        id: 'respiratory',
        label: 'Respiratory',
        type: 'select',
        source: 'section1',
        options: [
          { label: 'Normal parameters; no retractions', value: 0 },
          { label: '>10 above normal; accessory muscle use; 30–40% FiO₂ or ≥4 L/min', value: 1 },
          { label: '>20 above normal; retractions; >40% FiO₂ or ≥8 L/min', value: 2 },
          { label: '5 below normal with retractions and grunting; >50% FiO₂ or ≥10 L/min', value: 3 },
        ],
      },
      // Bonus point modifiers
      {
        id: 'persistent_vomiting_post_surgery',
        label: 'Persistent vomiting following surgery (add 2 if present)',
        type: 'boolean',
        value: 2,
        source: 'section1',
      },
    ],
    scoring: {
      method: 'sum',
      ranges: [
        { min: 0, max: 2, risk: 'Low', interpretation: 'Score 0–2: Low risk; routine monitoring per unit protocol; reassess at standard intervals' },
        { min: 3, max: 3, risk: 'Low-Moderate', interpretation: 'Score 3: Increase monitoring frequency; bedside nursing reassessment; inform charge nurse' },
        { min: 4, max: 4, risk: 'Moderate', interpretation: 'Score 4: Notify attending/resident; consider rapid response team evaluation; reassess q30 min' },
        { min: 5, max: 12, risk: 'High', interpretation: 'Score ≥5: Immediate physician evaluation; activate rapid response team; consider emergent PICU transfer; reassess q15 min or continuously' },
      ],
    },
    suggestedTreatments: {
      High: ['immediate_physician_evaluation', 'rapid_response_team', 'picu_transfer_consideration', 'continuous_monitoring'],
      Moderate: ['physician_notification', 'increased_monitoring', 'diagnostic_workup'],
      'Low-Moderate': ['increased_monitoring_frequency', 'nursing_reassessment'],
      Low: ['routine_monitoring', 'reassess_per_unit_protocol'],
    },
  },

  // INFECTIOUS DISEASE — Rochester Criteria
  {
    id: 'rochester_criteria',
    name: 'Rochester Criteria',
    fullName: 'Rochester Criteria',
    category: 'INFECTIOUS DISEASE',
    application: 'Identifies febrile infants ≤60 days old at low risk of serious bacterial infection (SBI). ALL criteria must be met for low-risk classification (~1% SBI rate). Missing any criterion classifies the infant as high risk.',
    applicableChiefComplaints: ['fever', 'neonatal_fever', 'infant_fever', 'irritability'],
    keywords: ['Rochester', 'febrile infant', 'serious bacterial infection', 'SBI', 'neonatal fever', 'infant', 'low risk'],
    requiredTests: ['cbc', 'ua', 'stool_studies'],
    components: [
      // Clinical criteria
      {
        id: 'previously_healthy',
        label: 'Previously healthy (term ≥37 wks, no perinatal antibiotics, no underlying illness, not hospitalized longer than mother)',
        type: 'boolean',
        value: 1,
        source: 'section1',
        autoPopulateFrom: 'narrative_analysis',
      },
      {
        id: 'well_appearing',
        label: 'Well-appearing (not toxic-appearing)',
        type: 'boolean',
        value: 1,
        source: 'section1',
        autoPopulateFrom: 'narrative_analysis',
      },
      {
        id: 'no_focal_infection',
        label: 'No focal bacterial infection on exam (no otitis media, soft tissue infection, bone/joint infection)',
        type: 'boolean',
        value: 1,
        source: 'section1',
      },
      // Lab criteria
      {
        id: 'wbc_normal',
        label: 'WBC 5,000–15,000/µL',
        type: 'boolean',
        value: 1,
        source: 'section2',
        autoPopulateFrom: 'test_result',
      },
      {
        id: 'bands_normal',
        label: 'Band count <1,500/µL (band-to-neutrophil ratio ≤0.2)',
        type: 'boolean',
        value: 1,
        source: 'section2',
        autoPopulateFrom: 'test_result',
      },
      {
        id: 'ua_normal',
        label: 'UA: <10 WBC/hpf on centrifuged specimen (no UTI)',
        type: 'boolean',
        value: 1,
        source: 'section2',
        autoPopulateFrom: 'test_result',
      },
      {
        id: 'stool_normal',
        label: 'Stool: <5 WBC/hpf (if diarrhea present)',
        type: 'boolean',
        value: 1,
        source: 'section2',
        autoPopulateFrom: 'test_result',
      },
    ],
    scoring: {
      method: 'threshold',
      ranges: [
        { min: 7, max: 7, risk: 'Low', interpretation: 'ALL 7 criteria met → Low risk (~1% SBI rate); may be considered for outpatient management with close 24–48h follow-up; shared decision-making with family required' },
        { min: 0, max: 6, risk: 'High', interpretation: 'ANY criterion NOT met → Not low risk; full sepsis evaluation; blood + urine cultures; LP strongly considered; empiric antibiotics; admit for observation' },
      ],
    },
    suggestedTreatments: {
      High: ['blood_cx', 'ua', 'urine_cx', 'lumbar_puncture', 'empiric_ampicillin_gentamicin', 'admit'],
      Low: ['blood_cx', 'ua', 'urine_cx', 'discharge_with_strict_return_precautions', 'followup_24_48h'],
    },
  },

  // PROCEDURAL / AIRWAY — LEMON Assessment
  {
    id: 'lemon',
    name: 'LEMON Assessment',
    fullName: 'LEMON Assessment (Difficult Intubation Prediction)',
    category: 'PROCEDURAL / AIRWAY',
    application: 'Predicts difficult laryngoscopy and intubation using five components. ANY positive component warrants preparation for a difficult airway. Endorsed by Emergency Airway Management (Walls & Murphy).',
    applicableChiefComplaints: ['airway_management', 'intubation', 'respiratory_failure', 'RSI', 'airway_obstruction'],
    keywords: ['LEMON', 'difficult intubation', 'airway', 'Mallampati', 'RSI', 'intubation', 'laryngoscopy', 'airway management'],
    components: [
      // L — Look externally
      {
        id: 'look_externally',
        label: 'L — Look Externally (facial trauma, beard, large incisors, morbid obesity, dysmorphic features)',
        type: 'boolean',
        value: 1,
        source: 'section1',
        autoPopulateFrom: 'narrative_analysis',
      },
      // E — Evaluate 3-3-2 Rule
      {
        id: 'evaluate_332',
        label: 'E — Evaluate 3-3-2 Rule (mouth opening <3 fingers, hyoid–chin <3 fingers, thyromental <2 fingers)',
        type: 'boolean',
        value: 1,
        source: 'section1',
      },
      // M — Mallampati
      {
        id: 'mallampati',
        label: 'M — Mallampati Class III or IV (soft palate not visible; Class IV = only hard palate visible)',
        type: 'select',
        source: 'section1',
        options: [
          { label: 'Class I: Full visualization of soft palate, fauces, uvula, and anterior and posterior tonsillar pillars', value: 0 },
          { label: 'Class II: Soft palate, fauces, and uvula visible', value: 0 },
          { label: 'Class III: Soft palate and base of uvula visible only', value: 1 },
          { label: 'Class IV: Only hard palate visible', value: 1 },
        ],
      },
      // O — Obstruction
      {
        id: 'obstruction',
        label: 'O — Obstruction/Obesity (epiglottitis, Ludwig\'s angina, tumor, foreign body, or morbid obesity)',
        type: 'boolean',
        value: 1,
        source: 'section1',
        autoPopulateFrom: 'narrative_analysis',
      },
      // N — Neck mobility
      {
        id: 'neck_mobility',
        label: 'N — Neck Mobility reduced (cervical immobilization, arthritis, ankylosing spondylitis, halo device)',
        type: 'boolean',
        value: 1,
        source: 'section1',
        autoPopulateFrom: 'narrative_analysis',
      },
    ],
    scoring: {
      method: 'threshold',
      ranges: [
        { min: 0, max: 0, risk: 'Standard', interpretation: 'No positive LEMON components: Standard airway anticipated; proceed with standard RSI; have basic rescue equipment at bedside' },
        { min: 1, max: 5, risk: 'High', interpretation: 'ANY positive component: Difficult intubation anticipated; activate difficult airway protocol; pre-oxygenate aggressively; have video laryngoscope as primary; prepare surgical airway backup; consider awake intubation if cooperative; Mallampati III/IV alone significantly predicts difficult laryngoscopy' },
      ],
    },
    suggestedTreatments: {
      High: [
        'video_laryngoscope_primary',
        'bougie_ready',
        'supraglottic_airway_backup',
        'surgical_airway_setup_at_bedside',
        'pre_oxygenation_bvm_hfnc',
        'consider_awake_intubation',
        'two_person_technique',
        'anesthesia_ent_backup_notification',
      ],
      Standard: [
        'standard_rsi_setup',
        'pre_oxygenation',
        'bougie_available',
        'backup_device_accessible',
      ],
    },
  },
]
