/**
 * Seed Test Library
 * Populates the `testLibrary` Firestore collection with the canonical ER test catalog.
 *
 * Usage: cd backend && NODE_PATH=./node_modules npx tsx ../scripts/seed-test-library.ts
 *
 * Prerequisites:
 * - GOOGLE_APPLICATION_CREDENTIALS or GOOGLE_APPLICATION_CREDENTIALS_JSON env var
 *
 * Idempotent: Uses deterministic doc IDs (test.id), so re-running overwrites identically.
 */

import admin from 'firebase-admin'
import fs from 'node:fs'
import path from 'node:path'

// Initialize Firebase Admin
const serviceAccountJson = process.env.GOOGLE_APPLICATION_CREDENTIALS_JSON
const serviceAccountPath = process.env.GOOGLE_APPLICATION_CREDENTIALS

if (serviceAccountJson) {
  admin.initializeApp({
    credential: admin.credential.cert(JSON.parse(serviceAccountJson)),
  })
} else if (serviceAccountPath) {
  const content = fs.readFileSync(path.resolve(serviceAccountPath), 'utf8')
  admin.initializeApp({
    credential: admin.credential.cert(JSON.parse(content)),
  })
} else {
  admin.initializeApp()
}

const db = admin.firestore()

// ---------------------------------------------------------------------------
// Type definitions (inline to keep script self-contained)
// ---------------------------------------------------------------------------

type TestCategory = 'labs' | 'imaging' | 'procedures_poc'

interface TestSeed {
  id: string
  name: string
  category: TestCategory
  subcategory: string
  commonIndications: string[]
  unit: string | null
  normalRange: string | null
  quickFindings: string[] | null
  feedsCdrs: string[]
}

// ---------------------------------------------------------------------------
// Complete Test Catalog (~240 tests)
// ---------------------------------------------------------------------------

const tests: TestSeed[] = [
  // ===== LABS =====
  { id: 'cbc', name: 'CBC', category: 'labs', subcategory: 'hematology', commonIndications: ['anemia', 'infection', 'bleeding'], unit: null, normalRange: null, quickFindings: null, feedsCdrs: [] },
  { id: 'bmp', name: 'BMP', category: 'labs', subcategory: 'chemistry', commonIndications: ['electrolytes', 'renal function', 'glucose'], unit: null, normalRange: null, quickFindings: null, feedsCdrs: [] },
  { id: 'cmp', name: 'CMP', category: 'labs', subcategory: 'chemistry', commonIndications: ['liver function', 'electrolytes', 'renal function'], unit: null, normalRange: null, quickFindings: null, feedsCdrs: [] },
  { id: 'mag', name: 'Magnesium', category: 'labs', subcategory: 'chemistry', commonIndications: ['electrolyte abnormality', 'seizure', 'arrhythmia'], unit: 'mEq/L', normalRange: '1.7-2.2', quickFindings: null, feedsCdrs: [] },
  { id: 'phos', name: 'Phosphorus', category: 'labs', subcategory: 'chemistry', commonIndications: ['electrolyte abnormality', 'renal disease'], unit: 'mg/dL', normalRange: '2.5-4.5', quickFindings: null, feedsCdrs: [] },
  { id: 'lfts', name: 'LFTs', category: 'labs', subcategory: 'hepatic', commonIndications: ['liver disease', 'abdominal pain', 'jaundice'], unit: null, normalRange: null, quickFindings: null, feedsCdrs: [] },
  { id: 'lipase', name: 'Lipase', category: 'labs', subcategory: 'hepatic', commonIndications: ['pancreatitis', 'abdominal pain'], unit: 'U/L', normalRange: '0-160', quickFindings: null, feedsCdrs: [] },
  { id: 'amylase', name: 'Amylase', category: 'labs', subcategory: 'hepatic', commonIndications: ['pancreatitis', 'abdominal pain'], unit: 'U/L', normalRange: '30-110', quickFindings: null, feedsCdrs: [] },
  { id: 'coags_inr', name: 'Coags/INR', category: 'labs', subcategory: 'hematology', commonIndications: ['bleeding', 'anticoagulation', 'liver disease'], unit: null, normalRange: null, quickFindings: null, feedsCdrs: ['wells_dvt'] },
  { id: 'troponin', name: 'Troponin', category: 'labs', subcategory: 'cardiac', commonIndications: ['chest pain', 'ACS', 'myocardial injury'], unit: 'ng/mL', normalRange: '<0.04', quickFindings: null, feedsCdrs: ['heart'] },
  { id: 'bnp', name: 'BNP/proBNP', category: 'labs', subcategory: 'cardiac', commonIndications: ['dyspnea', 'CHF', 'volume overload'], unit: 'pg/mL', normalRange: '<100', quickFindings: null, feedsCdrs: ['heart'] },
  { id: 'd_dimer', name: 'D-dimer', category: 'labs', subcategory: 'hematology', commonIndications: ['PE', 'DVT', 'DIC'], unit: 'ng/mL FEU', normalRange: '<500', quickFindings: null, feedsCdrs: ['wells_pe', 'wells_dvt'] },
  { id: 'lactate', name: 'Lactate', category: 'labs', subcategory: 'chemistry', commonIndications: ['sepsis', 'shock', 'tissue hypoperfusion'], unit: 'mmol/L', normalRange: '0.5-2.0', quickFindings: null, feedsCdrs: ['sepsis'] },
  { id: 'ua', name: 'Urinalysis', category: 'labs', subcategory: 'genitourinary', commonIndications: ['UTI', 'hematuria', 'renal disease'], unit: null, normalRange: null, quickFindings: null, feedsCdrs: [] },
  { id: 'ucg', name: 'UCG (Urine Pregnancy)', category: 'labs', subcategory: 'genitourinary', commonIndications: ['pregnancy', 'abdominal pain', 'vaginal bleeding'], unit: null, normalRange: null, quickFindings: null, feedsCdrs: [] },
  { id: 'blood_cx', name: 'Blood Cultures', category: 'labs', subcategory: 'infectious', commonIndications: ['sepsis', 'fever', 'bacteremia'], unit: null, normalRange: null, quickFindings: null, feedsCdrs: ['sepsis'] },
  { id: 'type_screen', name: 'Type & Screen', category: 'labs', subcategory: 'hematology', commonIndications: ['transfusion', 'bleeding', 'surgical prep'], unit: null, normalRange: null, quickFindings: null, feedsCdrs: [] },
  { id: 'vbg_abg', name: 'VBG/ABG', category: 'labs', subcategory: 'chemistry', commonIndications: ['respiratory distress', 'acid-base', 'metabolic'], unit: null, normalRange: null, quickFindings: null, feedsCdrs: [] },
  { id: 'esr_crp', name: 'ESR/CRP', category: 'labs', subcategory: 'inflammatory', commonIndications: ['inflammation', 'infection', 'autoimmune'], unit: null, normalRange: null, quickFindings: null, feedsCdrs: [] },
  { id: 'tsh', name: 'TSH', category: 'labs', subcategory: 'endocrine', commonIndications: ['thyroid disease', 'fatigue', 'weight change'], unit: 'mIU/L', normalRange: '0.4-4.0', quickFindings: null, feedsCdrs: [] },
  { id: 'free_t4', name: 'Free T4', category: 'labs', subcategory: 'endocrine', commonIndications: ['thyroid storm', 'myxedema coma', 'abnormal TSH', 'thyrotoxicosis'], unit: 'ng/dL', normalRange: '0.8-1.8', quickFindings: null, feedsCdrs: ['burch_wartofsky'] },
  { id: 'cortisol', name: 'Random Cortisol', category: 'labs', subcategory: 'endocrine', commonIndications: ['adrenal crisis', 'refractory hypotension', 'septic shock', 'altered mental status'], unit: 'ug/dL', normalRange: '6-23', quickFindings: null, feedsCdrs: [] },
  { id: 'hba1c', name: 'Hemoglobin A1c', category: 'labs', subcategory: 'endocrine', commonIndications: ['diabetes evaluation', 'DKA', 'hyperglycemia', 'glycemic control'], unit: '%', normalRange: '<5.7', quickFindings: null, feedsCdrs: [] },
  { id: 'pth', name: 'Parathyroid Hormone (PTH)', category: 'labs', subcategory: 'endocrine', commonIndications: ['hypercalcemia', 'hypocalcemia', 'renal disease', 'bone pain'], unit: 'pg/mL', normalRange: '15-65', quickFindings: null, feedsCdrs: [] },
  { id: 'vitamin_d', name: 'Vitamin D (25-OH)', category: 'labs', subcategory: 'endocrine', commonIndications: ['hypocalcemia', 'bone disease', 'fatigue', 'muscle weakness'], unit: 'ng/mL', normalRange: '30-100', quickFindings: null, feedsCdrs: [] },
  { id: 'ldh', name: 'LDH', category: 'labs', subcategory: 'chemistry', commonIndications: ['hemolysis', 'tissue damage', 'malignancy'], unit: 'U/L', normalRange: '140-280', quickFindings: null, feedsCdrs: [] },
  { id: 'fibrinogen', name: 'Fibrinogen', category: 'labs', subcategory: 'hematology', commonIndications: ['DIC', 'bleeding', 'coagulopathy'], unit: 'mg/dL', normalRange: '200-400', quickFindings: null, feedsCdrs: [] },
  { id: 'haptoglobin', name: 'Haptoglobin', category: 'labs', subcategory: 'hematology', commonIndications: ['hemolysis', 'anemia'], unit: 'mg/dL', normalRange: '30-200', quickFindings: null, feedsCdrs: [] },
  { id: 'retic_ct', name: 'Reticulocyte Count', category: 'labs', subcategory: 'hematology', commonIndications: ['anemia', 'bone marrow response'], unit: '%', normalRange: '0.5-2.5', quickFindings: null, feedsCdrs: [] },
  { id: 'ammonia', name: 'Ammonia', category: 'labs', subcategory: 'chemistry', commonIndications: ['hepatic encephalopathy', 'altered mental status'], unit: 'umol/L', normalRange: '15-45', quickFindings: null, feedsCdrs: [] },
  { id: 'ethanol', name: 'Ethanol Level', category: 'labs', subcategory: 'toxicology', commonIndications: ['intoxication', 'altered mental status'], unit: 'mg/dL', normalRange: '0', quickFindings: null, feedsCdrs: [] },
  { id: 'salicylate', name: 'Salicylate Level', category: 'labs', subcategory: 'toxicology', commonIndications: ['overdose', 'tinnitus', 'metabolic acidosis'], unit: 'mg/dL', normalRange: '<30', quickFindings: null, feedsCdrs: [] },
  { id: 'apap', name: 'Acetaminophen Level', category: 'labs', subcategory: 'toxicology', commonIndications: ['overdose', 'liver injury'], unit: 'ug/mL', normalRange: '<20', quickFindings: null, feedsCdrs: ['rumack_matthew'] },
  { id: 'urine_tox', name: 'Urine Tox Screen', category: 'labs', subcategory: 'toxicology', commonIndications: ['overdose', 'altered mental status', 'drug screening'], unit: null, normalRange: null, quickFindings: null, feedsCdrs: [] },
  { id: 'uds', name: 'Urine Drug Screen', category: 'labs', subcategory: 'toxicology', commonIndications: ['overdose', 'altered mental status', 'drug screening'], unit: null, normalRange: null, quickFindings: null, feedsCdrs: [] },
  { id: 'osmolality', name: 'Osmolality', category: 'labs', subcategory: 'chemistry', commonIndications: ['hyponatremia', 'toxic ingestion', 'osmolar gap'], unit: 'mOsm/kg', normalRange: '275-295', quickFindings: null, feedsCdrs: [] },
  { id: 'procalcitonin', name: 'Procalcitonin', category: 'labs', subcategory: 'infectious', commonIndications: ['sepsis', 'infection differentiation', 'antibiotic stewardship'], unit: 'ng/mL', normalRange: '<0.1', quickFindings: null, feedsCdrs: [] },
  { id: 'ck_cpk', name: 'CK/CPK', category: 'labs', subcategory: 'chemistry', commonIndications: ['rhabdomyolysis', 'muscle injury', 'cardiac'], unit: 'U/L', normalRange: '22-198', quickFindings: null, feedsCdrs: [] },
  { id: 'ionized_calcium', name: 'Ionized Calcium', category: 'labs', subcategory: 'chemistry', commonIndications: ['hypocalcemia', 'hypercalcemia', 'hypoalbuminemia', 'cardiac arrest', 'massive transfusion'], unit: 'mg/dL', normalRange: '4.8-5.6', quickFindings: null, feedsCdrs: [] },
  { id: 'uric_acid', name: 'Uric Acid', category: 'labs', subcategory: 'chemistry', commonIndications: ['gout', 'tumor lysis syndrome', 'renal disease', 'joint pain'], unit: 'mg/dL', normalRange: '3.5-7.2', quickFindings: null, feedsCdrs: [] },
  { id: 'myoglobin', name: 'Myoglobin', category: 'labs', subcategory: 'chemistry', commonIndications: ['rhabdomyolysis', 'crush injury', 'compartment syndrome'], unit: 'ng/mL', normalRange: '<85', quickFindings: null, feedsCdrs: [] },
  { id: 'urine_electrolytes', name: 'Urine Electrolytes (FeNa)', category: 'labs', subcategory: 'chemistry', commonIndications: ['acute kidney injury', 'hyponatremia', 'prerenal vs renal AKI'], unit: null, normalRange: null, quickFindings: ['FeNa <1% (prerenal)', 'FeNa >2% (intrinsic renal)', 'FeNa 1-2% (indeterminate)'], feedsCdrs: [] },
  { id: 'folate_b12', name: 'Folate/Vitamin B12', category: 'labs', subcategory: 'chemistry', commonIndications: ['macrocytic anemia', 'altered mental status', 'neuropathy', 'malnutrition'], unit: null, normalRange: null, quickFindings: null, feedsCdrs: [] },
  { id: 'beta_hydroxybutyrate', name: 'Beta-Hydroxybutyrate', category: 'labs', subcategory: 'chemistry', commonIndications: ['DKA', 'ketoacidosis', 'alcoholic ketoacidosis', 'starvation ketosis'], unit: 'mmol/L', normalRange: '<0.6', quickFindings: null, feedsCdrs: [] },
  { id: 'hcg_quant', name: 'Quantitative beta-HCG', category: 'labs', subcategory: 'genitourinary', commonIndications: ['ectopic pregnancy', 'pregnancy quantification', 'vaginal bleeding'], unit: 'mIU/mL', normalRange: null, quickFindings: null, feedsCdrs: [] },
  { id: 'urine_cx', name: 'Urine Culture', category: 'labs', subcategory: 'infectious', commonIndications: ['UTI confirmation', 'recurrent UTI', 'pyelonephritis'], unit: null, normalRange: null, quickFindings: ['No growth', 'Growth >100k CFU', 'Mixed flora'], feedsCdrs: [] },
  { id: 'stool_studies', name: 'Stool Studies', category: 'labs', subcategory: 'infectious', commonIndications: ['C. diff', 'diarrhea', 'O&P', 'infectious colitis'], unit: null, normalRange: null, quickFindings: ['C. diff positive', 'C. diff negative', 'O&P positive'], feedsCdrs: [] },
  { id: 'blood_type_crossmatch', name: 'Type & Crossmatch', category: 'labs', subcategory: 'hematology', commonIndications: ['massive transfusion', 'surgical prep', 'GI bleed'], unit: null, normalRange: null, quickFindings: null, feedsCdrs: [] },
  { id: 'peripheral_smear', name: 'Peripheral Blood Smear', category: 'labs', subcategory: 'hematology', commonIndications: ['TTP/HUS', 'hemolysis', 'thrombocytopenia', 'anemia workup', 'DIC'], unit: null, normalRange: null, quickFindings: ['Normal morphology', 'Schistocytes', 'Sickle cells', 'Spherocytes', 'Blasts'], feedsCdrs: [] },
  { id: 'direct_coombs', name: 'Direct Coombs (DAT)', category: 'labs', subcategory: 'hematology', commonIndications: ['autoimmune hemolytic anemia', 'hemolysis', 'transfusion reaction', 'neonatal jaundice'], unit: null, normalRange: null, quickFindings: ['Positive', 'Negative'], feedsCdrs: [] },
  { id: 'thromboelastography', name: 'TEG/ROTEM', category: 'labs', subcategory: 'hematology', commonIndications: ['massive transfusion', 'coagulopathy', 'trauma', 'DIC', 'liver disease'], unit: null, normalRange: null, quickFindings: ['Normal', 'Hypercoagulable', 'Hypocoagulable', 'Fibrinolysis'], feedsCdrs: [] },
  { id: 'anti_xa', name: 'Anti-Xa Level', category: 'labs', subcategory: 'hematology', commonIndications: ['LMWH monitoring', 'DOAC level assessment', 'bleeding on anticoagulation', 'renal dosing'], unit: 'IU/mL', normalRange: null, quickFindings: ['Therapeutic', 'Subtherapeutic', 'Supratherapeutic'], feedsCdrs: [] },

  // New hepatic
  { id: 'gg_tp', name: 'GGT', category: 'labs', subcategory: 'hepatic', commonIndications: ['biliary obstruction', 'alcohol use', 'elevated alkaline phosphatase'], unit: 'U/L', normalRange: '8-61', quickFindings: null, feedsCdrs: [] },

  // New infectious
  { id: 'gc_chlamydia', name: 'GC/Chlamydia NAAT', category: 'labs', subcategory: 'infectious', commonIndications: ['STI screening', 'pelvic pain', 'urethritis', 'cervicitis', 'vaginal discharge'], unit: null, normalRange: null, quickFindings: ['GC positive', 'Chlamydia positive', 'Both positive', 'Both negative'], feedsCdrs: [] },
  { id: 'wound_cx', name: 'Wound Culture', category: 'labs', subcategory: 'infectious', commonIndications: ['wound infection', 'abscess', 'cellulitis', 'bite wound'], unit: null, normalRange: null, quickFindings: ['No growth', 'MRSA', 'MSSA', 'Strep', 'Polymicrobial'], feedsCdrs: [] },
  { id: 'throat_cx', name: 'Throat Culture', category: 'labs', subcategory: 'infectious', commonIndications: ['pharyngitis', 'negative rapid strep', 'peritonsillar abscess'], unit: null, normalRange: null, quickFindings: ['GAS positive', 'Negative', 'Normal flora'], feedsCdrs: ['centor_mcisaac'] },
  { id: 'hepatitis_panel', name: 'Hepatitis Panel', category: 'labs', subcategory: 'infectious', commonIndications: ['elevated LFTs', 'jaundice', 'liver failure', 'needle stick', 'cirrhosis'], unit: null, normalRange: null, quickFindings: ['Hep A IgM positive', 'Hep B sAg positive', 'Hep C Ab positive', 'All negative'], feedsCdrs: [] },
  { id: 'hiv_rapid', name: 'Rapid HIV', category: 'labs', subcategory: 'infectious', commonIndications: ['HIV screening', 'needle stick', 'opportunistic infection', 'STI screening'], unit: null, normalRange: null, quickFindings: ['Positive', 'Negative'], feedsCdrs: [] },
  { id: 'mono_spot', name: 'Monospot (Heterophile Ab)', category: 'labs', subcategory: 'infectious', commonIndications: ['pharyngitis', 'fatigue', 'lymphadenopathy', 'splenomegaly'], unit: null, normalRange: null, quickFindings: ['Positive', 'Negative'], feedsCdrs: [] },
  { id: 'respiratory_panel', name: 'Respiratory Pathogen Panel', category: 'labs', subcategory: 'infectious', commonIndications: ['respiratory illness', 'fever', 'pneumonia', 'bronchiolitis', 'immunocompromised'], unit: null, normalRange: null, quickFindings: ['Influenza A', 'Influenza B', 'RSV', 'SARS-CoV-2', 'Rhinovirus', 'Adenovirus', 'Parainfluenza', 'Negative'], feedsCdrs: [] },
  { id: 'syphilis_rpr', name: 'Syphilis RPR/VDRL', category: 'labs', subcategory: 'infectious', commonIndications: ['STI screening', 'rash', 'neurologic symptoms', 'pregnancy screening'], unit: null, normalRange: null, quickFindings: ['Reactive', 'Non-reactive'], feedsCdrs: [] },
  { id: 'lyme_titer', name: 'Lyme Disease Titer', category: 'labs', subcategory: 'infectious', commonIndications: ['tick bite', 'erythema migrans', 'facial palsy', 'arthritis', 'heart block'], unit: null, normalRange: null, quickFindings: ['IgM positive', 'IgG positive', 'Negative'], feedsCdrs: [] },
  { id: 'tb_quantiferon', name: 'TB QuantiFERON Gold', category: 'labs', subcategory: 'infectious', commonIndications: ['tuberculosis screening', 'immunocompromised', 'exposure', 'cavitary lung disease'], unit: null, normalRange: null, quickFindings: ['Positive', 'Negative', 'Indeterminate'], feedsCdrs: [] },
  { id: 'malaria_smear', name: 'Malaria Smear/RDT', category: 'labs', subcategory: 'infectious', commonIndications: ['travel fever', 'malaria endemic exposure', 'cyclic fevers', 'thrombocytopenia after travel'], unit: null, normalRange: null, quickFindings: ['P. falciparum', 'P. vivax', 'P. malariae', 'Negative'], feedsCdrs: [] },

  // New inflammatory
  { id: 'tryptase', name: 'Serum Tryptase', category: 'labs', subcategory: 'inflammatory', commonIndications: ['anaphylaxis confirmation', 'mast cell activation', 'post-resuscitation'], unit: 'ng/mL', normalRange: '<11.4', quickFindings: null, feedsCdrs: [] },

  // New toxicology
  { id: 'digoxin_level', name: 'Digoxin Level', category: 'labs', subcategory: 'toxicology', commonIndications: ['digoxin toxicity', 'arrhythmia', 'nausea on digoxin', 'bradycardia'], unit: 'ng/mL', normalRange: '0.8-2.0', quickFindings: null, feedsCdrs: [] },
  { id: 'lithium_level', name: 'Lithium Level', category: 'labs', subcategory: 'toxicology', commonIndications: ['lithium toxicity', 'tremor', 'altered mental status', 'renal impairment on lithium'], unit: 'mEq/L', normalRange: '0.6-1.2', quickFindings: null, feedsCdrs: [] },
  { id: 'valproic_acid_level', name: 'Valproic Acid Level', category: 'labs', subcategory: 'toxicology', commonIndications: ['VPA toxicity', 'seizure management', 'altered mental status', 'hepatotoxicity'], unit: 'ug/mL', normalRange: '50-100', quickFindings: null, feedsCdrs: [] },
  { id: 'phenytoin_level', name: 'Phenytoin Level', category: 'labs', subcategory: 'toxicology', commonIndications: ['seizure management', 'phenytoin toxicity', 'nystagmus', 'ataxia'], unit: 'ug/mL', normalRange: '10-20', quickFindings: null, feedsCdrs: [] },
  { id: 'carbamazepine_level', name: 'Carbamazepine Level', category: 'labs', subcategory: 'toxicology', commonIndications: ['carbamazepine toxicity', 'seizure management', 'ataxia', 'diplopia'], unit: 'ug/mL', normalRange: '4-12', quickFindings: null, feedsCdrs: [] },
  { id: 'carboxyhemoglobin', name: 'Carboxyhemoglobin (CO)', category: 'labs', subcategory: 'toxicology', commonIndications: ['carbon monoxide exposure', 'headache', 'smoke inhalation', 'altered mental status'], unit: '%', normalRange: '<3', quickFindings: null, feedsCdrs: [] },
  { id: 'methemoglobin', name: 'Methemoglobin Level', category: 'labs', subcategory: 'toxicology', commonIndications: ['cyanosis', 'dapsone toxicity', 'benzocaine exposure', 'SpO2 gap'], unit: '%', normalRange: '<1.5', quickFindings: null, feedsCdrs: [] },
  { id: 'iron_studies', name: 'Iron/TIBC/Ferritin', category: 'labs', subcategory: 'toxicology', commonIndications: ['iron overdose', 'iron deficiency anemia', 'anemia workup'], unit: 'ug/dL', normalRange: '60-170', quickFindings: null, feedsCdrs: [] },
  { id: 'ethylene_glycol', name: 'Ethylene Glycol Level', category: 'labs', subcategory: 'toxicology', commonIndications: ['toxic alcohol ingestion', 'osmolar gap', 'anion gap acidosis', 'renal failure'], unit: 'mg/dL', normalRange: '0', quickFindings: null, feedsCdrs: [] },
  { id: 'methanol_level', name: 'Methanol Level', category: 'labs', subcategory: 'toxicology', commonIndications: ['toxic alcohol ingestion', 'vision loss', 'osmolar gap', 'anion gap acidosis'], unit: 'mg/dL', normalRange: '0', quickFindings: null, feedsCdrs: [] },
  { id: 'phenobarbital_level', name: 'Phenobarbital Level', category: 'labs', subcategory: 'toxicology', commonIndications: ['seizure management', 'barbiturate toxicity', 'status epilepticus'], unit: 'ug/mL', normalRange: '15-40', quickFindings: null, feedsCdrs: [] },
  { id: 'theophylline_level', name: 'Theophylline Level', category: 'labs', subcategory: 'toxicology', commonIndications: ['theophylline toxicity', 'seizure', 'tachycardia', 'COPD management'], unit: 'ug/mL', normalRange: '10-20', quickFindings: null, feedsCdrs: [] },
  { id: 'cyanide_level', name: 'Cyanide Level', category: 'labs', subcategory: 'toxicology', commonIndications: ['smoke inhalation', 'cyanide exposure', 'lactic acidosis with fire exposure'], unit: 'mg/L', normalRange: '<0.1', quickFindings: null, feedsCdrs: [] },
  { id: 'cholinesterase', name: 'Cholinesterase Level', category: 'labs', subcategory: 'toxicology', commonIndications: ['organophosphate poisoning', 'nerve agent exposure', 'SLUDGE symptoms'], unit: 'U/L', normalRange: '5320-12920', quickFindings: null, feedsCdrs: [] },

  // New specialty labs
  { id: 'fobt', name: 'Fecal Occult Blood Test', category: 'labs', subcategory: 'gastrointestinal', commonIndications: ['GI bleed', 'anemia', 'melena', 'occult blood loss'], unit: null, normalRange: null, quickFindings: ['Positive', 'Negative'], feedsCdrs: [] },
  { id: 'csf_analysis', name: 'CSF Analysis', category: 'labs', subcategory: 'neurologic', commonIndications: ['meningitis', 'encephalitis', 'SAH', 'CNS infection'], unit: null, normalRange: null, quickFindings: ['Normal', 'Bacterial pattern', 'Viral pattern', 'Xanthochromia', 'Elevated protein', 'Elevated WBC'], feedsCdrs: [] },
  { id: 'synovial_fluid', name: 'Synovial Fluid Analysis', category: 'labs', subcategory: 'rheumatologic', commonIndications: ['septic arthritis', 'gout', 'pseudogout', 'joint effusion'], unit: null, normalRange: null, quickFindings: ['Non-inflammatory (<2k WBC)', 'Inflammatory (2-50k WBC)', 'Septic (>50k WBC)', 'MSU crystals (gout)', 'CPPD crystals (pseudogout)'], feedsCdrs: ['kocher_criteria'] },
  { id: 'kleihauer_betke', name: 'Kleihauer-Betke Test', category: 'labs', subcategory: 'obstetric', commonIndications: ['fetomaternal hemorrhage', 'Rh-negative mother', 'trauma in pregnancy', 'vaginal bleeding in pregnancy'], unit: null, normalRange: null, quickFindings: ['Positive (fetal cells detected)', 'Negative'], feedsCdrs: [] },
  { id: 'pleural_fluid_analysis', name: 'Pleural Fluid Analysis', category: 'labs', subcategory: 'pulmonary', commonIndications: ['pleural effusion', 'empyema', 'malignant effusion', 'parapneumonic effusion'], unit: null, normalRange: null, quickFindings: ['Transudative (Light criteria)', 'Exudative (Light criteria)', 'Empyema', 'Bloody', 'Chylous'], feedsCdrs: [] },

  // ===== IMAGING =====
  { id: 'ct_head', name: 'CT Head', category: 'imaging', subcategory: 'head_neck', commonIndications: ['headache', 'trauma', 'altered mental status', 'stroke'], unit: null, normalRange: null, quickFindings: ['Normal', 'Bleed', 'Mass', 'Edema', 'Midline shift'], feedsCdrs: ['canadian_ct_head'] },
  { id: 'ct_cspine', name: 'CT C-spine', category: 'imaging', subcategory: 'spine', commonIndications: ['trauma', 'neck pain', 'neurologic deficit'], unit: null, normalRange: null, quickFindings: ['Normal', 'Fracture', 'Subluxation', 'Degenerative'], feedsCdrs: ['nexus', 'canadian_cspine'] },
  { id: 'ct_chest', name: 'CT Chest', category: 'imaging', subcategory: 'chest', commonIndications: ['chest pain', 'dyspnea', 'trauma'], unit: null, normalRange: null, quickFindings: ['Normal', 'Consolidation', 'Effusion', 'Mass', 'Fracture'], feedsCdrs: [] },
  { id: 'cta_chest', name: 'CTA Chest', category: 'imaging', subcategory: 'chest', commonIndications: ['PE', 'aortic dissection', 'chest pain'], unit: null, normalRange: null, quickFindings: ['Normal', 'PE', 'Aortic dissection', 'Aneurysm'], feedsCdrs: ['wells_pe', 'perc'] },
  { id: 'ct_abd_pelv', name: 'CT Abdomen/Pelvis', category: 'imaging', subcategory: 'abdomen', commonIndications: ['abdominal pain', 'appendicitis', 'obstruction'], unit: null, normalRange: null, quickFindings: ['Normal', 'Appendicitis', 'Obstruction', 'Free fluid', 'Mass'], feedsCdrs: [] },
  { id: 'cta_head', name: 'CTA Head/Neck', category: 'imaging', subcategory: 'head_neck', commonIndications: ['stroke', 'vessel occlusion', 'dissection'], unit: null, normalRange: null, quickFindings: ['Normal', 'Occlusion', 'Stenosis', 'Aneurysm', 'Dissection'], feedsCdrs: [] },
  { id: 'xr_chest', name: 'Chest X-ray (CXR)', category: 'imaging', subcategory: 'chest', commonIndications: ['dyspnea', 'cough', 'chest pain', 'fever'], unit: null, normalRange: null, quickFindings: ['Normal', 'Infiltrate', 'Effusion', 'Pneumothorax', 'Cardiomegaly'], feedsCdrs: [] },
  { id: 'xr_ext', name: 'X-ray Extremity', category: 'imaging', subcategory: 'extremity', commonIndications: ['injury', 'pain', 'deformity'], unit: null, normalRange: null, quickFindings: ['Normal', 'Fracture', 'Dislocation', 'Soft tissue swelling'], feedsCdrs: ['ottawa_ankle', 'ottawa_knee'] },
  { id: 'xr_spine', name: 'X-ray Spine', category: 'imaging', subcategory: 'spine', commonIndications: ['back pain', 'trauma', 'compression fracture'], unit: null, normalRange: null, quickFindings: ['Normal', 'Fracture', 'Compression', 'Degenerative'], feedsCdrs: [] },
  { id: 'us_fast', name: 'US FAST', category: 'imaging', subcategory: 'abdomen', commonIndications: ['trauma', 'hypotension', 'abdominal pain'], unit: null, normalRange: null, quickFindings: ['Negative', 'Positive - free fluid', 'Positive - pericardial'], feedsCdrs: [] },
  { id: 'us_ruq', name: 'US RUQ (Gallbladder)', category: 'imaging', subcategory: 'abdomen', commonIndications: ['RUQ pain', 'cholecystitis', 'biliary disease'], unit: null, normalRange: null, quickFindings: ['Normal', 'Cholelithiasis', 'Cholecystitis', 'CBD dilation'], feedsCdrs: [] },
  { id: 'us_aorta', name: 'US Aorta', category: 'imaging', subcategory: 'abdomen', commonIndications: ['abdominal pain', 'AAA screening', 'hypotension'], unit: null, normalRange: null, quickFindings: ['Normal', 'AAA', 'Dissection flap'], feedsCdrs: [] },
  { id: 'us_soft_tissue', name: 'US Soft Tissue', category: 'imaging', subcategory: 'soft_tissue', commonIndications: ['abscess', 'cellulitis', 'foreign body'], unit: null, normalRange: null, quickFindings: ['Normal', 'Abscess', 'Cellulitis', 'Foreign body'], feedsCdrs: [] },
  { id: 'us_ob', name: 'US OB (Obstetric)', category: 'imaging', subcategory: 'obstetric', commonIndications: ['pregnancy', 'vaginal bleeding', 'abdominal pain'], unit: null, normalRange: null, quickFindings: ['IUP confirmed', 'No IUP', 'Ectopic', 'Free fluid'], feedsCdrs: [] },
  { id: 'us_renal', name: 'US Renal', category: 'imaging', subcategory: 'genitourinary', commonIndications: ['flank pain', 'renal colic', 'hematuria'], unit: null, normalRange: null, quickFindings: ['Normal', 'Hydronephrosis', 'Stone', 'Mass'], feedsCdrs: [] },
  { id: 'echo_tte', name: 'Echo TTE', category: 'imaging', subcategory: 'cardiac', commonIndications: ['dyspnea', 'chest pain', 'murmur', 'CHF'], unit: null, normalRange: null, quickFindings: ['Normal EF', 'Reduced EF', 'Wall motion abnormality', 'Pericardial effusion', 'Valve abnormality'], feedsCdrs: ['heart'] },
  { id: 'mri_brain', name: 'MRI Brain', category: 'imaging', subcategory: 'head_neck', commonIndications: ['stroke', 'seizure', 'mass'], unit: null, normalRange: null, quickFindings: ['Normal', 'Infarct', 'Mass', 'Hemorrhage'], feedsCdrs: [] },
  { id: 'fluoro', name: 'Fluoroscopy', category: 'imaging', subcategory: 'misc', commonIndications: ['reduction', 'foreign body', 'swallow study'], unit: null, normalRange: null, quickFindings: null, feedsCdrs: [] },
  { id: 'us_le_venous', name: 'LE Venous Duplex (DVT)', category: 'imaging', subcategory: 'vascular', commonIndications: ['DVT', 'leg swelling', 'unilateral edema'], unit: null, normalRange: null, quickFindings: ['Normal', 'DVT present', 'Superficial thrombosis'], feedsCdrs: ['wells_dvt'] },
  { id: 'us_pelvic', name: 'Pelvic Ultrasound', category: 'imaging', subcategory: 'obstetric', commonIndications: ['ectopic pregnancy', 'ovarian torsion', 'pelvic pain', 'vaginal bleeding'], unit: null, normalRange: null, quickFindings: ['Normal', 'Free fluid', 'Ovarian mass', 'Ectopic'], feedsCdrs: [] },
  { id: 'cta_abd', name: 'CTA Abdomen/Pelvis', category: 'imaging', subcategory: 'abdomen', commonIndications: ['mesenteric ischemia', 'AAA', 'GI bleed', 'vascular emergency'], unit: null, normalRange: null, quickFindings: ['Normal', 'Mesenteric occlusion', 'AAA', 'Active extravasation'], feedsCdrs: [] },
  { id: 'xr_pelvis', name: 'X-ray Pelvis', category: 'imaging', subcategory: 'extremity', commonIndications: ['hip fracture', 'pelvic trauma', 'hip pain'], unit: null, normalRange: null, quickFindings: ['Normal', 'Fracture', 'Dislocation', 'Degenerative'], feedsCdrs: [] },
  { id: 'ct_face', name: 'CT Facial Bones', category: 'imaging', subcategory: 'head_neck', commonIndications: ['facial trauma', 'orbital fracture', 'midface fracture'], unit: null, normalRange: null, quickFindings: ['Normal', 'Orbital fracture', 'Nasal fracture', 'Le Fort fracture'], feedsCdrs: [] },
  { id: 'xr_abd', name: 'X-ray Abdomen (KUB)', category: 'imaging', subcategory: 'abdomen', commonIndications: ['obstruction', 'foreign body', 'constipation', 'kidney stone'], unit: null, normalRange: null, quickFindings: ['Normal', 'Obstruction', 'Free air', 'Calcification'], feedsCdrs: [] },

  // New head_neck imaging
  { id: 'ct_neck_soft', name: 'CT Neck Soft Tissue', category: 'imaging', subcategory: 'head_neck', commonIndications: ['peritonsillar abscess', 'retropharyngeal abscess', 'Ludwig angina', 'deep neck space infection', 'neck mass'], unit: null, normalRange: null, quickFindings: ['Normal', 'Peritonsillar abscess', 'Retropharyngeal abscess', 'Lymphadenopathy', 'Mass'], feedsCdrs: [] },
  { id: 'xr_neck_soft', name: 'X-ray Soft Tissue Neck', category: 'imaging', subcategory: 'head_neck', commonIndications: ['croup', 'epiglottitis', 'foreign body', 'retropharyngeal abscess'], unit: null, normalRange: null, quickFindings: ['Normal', 'Steeple sign (croup)', 'Thumbprint sign (epiglottitis)', 'Prevertebral widening', 'Foreign body'], feedsCdrs: [] },
  { id: 'ct_orbits', name: 'CT Orbits', category: 'imaging', subcategory: 'head_neck', commonIndications: ['orbital cellulitis', 'orbital abscess', 'globe rupture', 'retrobulbar hemorrhage'], unit: null, normalRange: null, quickFindings: ['Normal', 'Orbital cellulitis', 'Subperiosteal abscess', 'Retrobulbar hemorrhage', 'Foreign body'], feedsCdrs: [] },
  { id: 'ct_sinuses', name: 'CT Sinuses', category: 'imaging', subcategory: 'head_neck', commonIndications: ['sinusitis', 'orbital cellulitis', 'facial pain', 'periorbital swelling'], unit: null, normalRange: null, quickFindings: ['Normal', 'Sinus opacification', 'Air-fluid levels', 'Mucosal thickening', 'Orbital extension'], feedsCdrs: [] },
  { id: 'panorex', name: 'Panoramic Dental X-ray (Panorex)', category: 'imaging', subcategory: 'head_neck', commonIndications: ['mandible fracture', 'dental trauma', 'dental abscess', 'TMJ evaluation'], unit: null, normalRange: null, quickFindings: ['Normal', 'Mandible fracture', 'Dental fracture', 'Periapical abscess', 'TMJ abnormality'], feedsCdrs: [] },
  { id: 'us_ocular', name: 'Ocular Ultrasound', category: 'imaging', subcategory: 'head_neck', commonIndications: ['retinal detachment', 'vitreous hemorrhage', 'lens dislocation', 'elevated IOP concern', 'globe rupture'], unit: null, normalRange: null, quickFindings: ['Normal', 'Retinal detachment', 'Vitreous hemorrhage', 'Lens dislocation', 'Posterior vitreous detachment'], feedsCdrs: [] },

  // New chest imaging
  { id: 'vq_scan', name: 'V/Q Scan', category: 'imaging', subcategory: 'chest', commonIndications: ['PE (CTA contraindicated)', 'renal insufficiency', 'contrast allergy', 'pregnancy'], unit: null, normalRange: null, quickFindings: ['Normal', 'Low probability', 'Intermediate probability', 'High probability'], feedsCdrs: ['wells_pe'] },
  { id: 'us_lung', name: 'US Lung (POCUS)', category: 'imaging', subcategory: 'chest', commonIndications: ['dyspnea', 'pneumothorax', 'pleural effusion', 'pulmonary edema', 'pneumonia'], unit: null, normalRange: null, quickFindings: ['A-lines (normal/COPD)', 'B-lines (pulmonary edema)', 'Absent lung sliding (pneumothorax)', 'Effusion', 'Consolidation (hepatization)'], feedsCdrs: [] },
  { id: 'xr_ribs', name: 'X-ray Ribs', category: 'imaging', subcategory: 'chest', commonIndications: ['chest wall pain', 'trauma', 'rib fracture', 'flail chest'], unit: null, normalRange: null, quickFindings: ['Normal', 'Single rib fracture', 'Multiple rib fractures', 'Flail segment'], feedsCdrs: [] },

  // New extremity imaging
  { id: 'ct_extremity', name: 'CT Extremity', category: 'imaging', subcategory: 'extremity', commonIndications: ['occult fracture', 'complex fracture', 'calcaneus fracture', 'tibial plateau fracture'], unit: null, normalRange: null, quickFindings: ['Normal', 'Occult fracture', 'Comminuted fracture', 'Intra-articular extension', 'Foreign body'], feedsCdrs: [] },
  { id: 'mri_extremity', name: 'MRI Extremity', category: 'imaging', subcategory: 'extremity', commonIndications: ['occult hip fracture', 'scaphoid fracture', 'ligament injury', 'osteomyelitis', 'soft tissue mass'], unit: null, normalRange: null, quickFindings: ['Normal', 'Occult fracture', 'Ligament tear', 'Osteomyelitis', 'Effusion', 'Mass'], feedsCdrs: [] },

  // New spine imaging
  { id: 'ct_tl_spine', name: 'CT Thoracolumbar Spine', category: 'imaging', subcategory: 'spine', commonIndications: ['trauma', 'back pain', 'compression fracture', 'neurologic deficit'], unit: null, normalRange: null, quickFindings: ['Normal', 'Compression fracture', 'Burst fracture', 'Transverse process fracture', 'Degenerative'], feedsCdrs: [] },
  { id: 'mri_spine', name: 'MRI Spine', category: 'imaging', subcategory: 'spine', commonIndications: ['cord compression', 'cauda equina syndrome', 'epidural abscess', 'cancer with back pain'], unit: null, normalRange: null, quickFindings: ['Normal', 'Cord compression', 'Epidural abscess', 'Disc herniation', 'Metastatic disease'], feedsCdrs: [] },

  // New cardiac imaging
  { id: 'us_ivc', name: 'US IVC (Volume Assessment)', category: 'imaging', subcategory: 'cardiac', commonIndications: ['volume status assessment', 'hypotension', 'sepsis', 'fluid responsiveness'], unit: null, normalRange: null, quickFindings: ['Plethoric (>2.1cm, <50% collapse)', 'Normal', 'Flat/collapsing (volume responsive)', 'IVC >50% collapse with respiration'], feedsCdrs: ['sepsis'] },

  // New genitourinary imaging
  { id: 'us_testicular', name: 'US Testicular/Scrotal', category: 'imaging', subcategory: 'genitourinary', commonIndications: ['testicular torsion', 'scrotal pain', 'testicular mass', 'epididymitis'], unit: null, normalRange: null, quickFindings: ['Normal', 'Torsion (absent flow)', 'Epididymitis', 'Hydrocele', 'Mass'], feedsCdrs: [] },

  // New vascular imaging
  { id: 'us_ue_venous', name: 'UE Venous Duplex', category: 'imaging', subcategory: 'vascular', commonIndications: ['upper extremity DVT', 'arm swelling', 'PICC-associated thrombosis', 'catheter-related thrombosis'], unit: null, normalRange: null, quickFindings: ['Normal', 'DVT present', 'Superficial thrombosis'], feedsCdrs: [] },
  { id: 'us_carotid', name: 'Carotid Duplex', category: 'imaging', subcategory: 'vascular', commonIndications: ['TIA', 'stroke', 'carotid bruit', 'amaurosis fugax'], unit: null, normalRange: null, quickFindings: ['Normal', 'Stenosis <50%', 'Stenosis 50-69%', 'Stenosis 70-99%', 'Occlusion'], feedsCdrs: ['abcd2'] },
  { id: 'ct_angio_chest_abd', name: 'CTA Chest/Abdomen/Pelvis', category: 'imaging', subcategory: 'vascular', commonIndications: ['aortic dissection', 'polytrauma', 'ruptured AAA', 'aortic emergency'], unit: null, normalRange: null, quickFindings: ['Normal', 'Aortic dissection Type A', 'Aortic dissection Type B', 'AAA with rupture', 'Active hemorrhage'], feedsCdrs: [] },
  { id: 'ct_angio_extremity', name: 'CTA Extremity', category: 'imaging', subcategory: 'vascular', commonIndications: ['vascular injury', 'limb ischemia', 'penetrating extremity trauma', 'absent distal pulses'], unit: null, normalRange: null, quickFindings: ['Normal vasculature', 'Vessel occlusion', 'Active extravasation', 'Pseudoaneurysm', 'AV fistula'], feedsCdrs: [] },

  // New gastrointestinal imaging
  { id: 'swallow_study', name: 'Esophagram/Swallow Study', category: 'imaging', subcategory: 'gastrointestinal', commonIndications: ['esophageal foreign body', 'esophageal perforation', 'dysphagia', 'Boerhaave syndrome'], unit: null, normalRange: null, quickFindings: ['Normal', 'Foreign body', 'Perforation/leak', 'Stricture', 'Obstruction'], feedsCdrs: [] },

  // ===== PROCEDURES/POC =====
  { id: 'ecg_12lead', name: 'ECG (12-lead)', category: 'procedures_poc', subcategory: 'cardiac', commonIndications: ['chest pain', 'palpitations', 'syncope', 'dyspnea'], unit: null, normalRange: null, quickFindings: ['Normal sinus', 'ST elevation', 'ST depression', 'Afib', 'SVT', 'VT', 'BBB', 'STEMI equivalent'], feedsCdrs: ['heart', 'sgarbossa'] },
  { id: 'ecg_repeat', name: 'Repeat ECG', category: 'procedures_poc', subcategory: 'cardiac', commonIndications: ['interval change', 'chest pain', 'serial monitoring'], unit: null, normalRange: null, quickFindings: ['Unchanged', 'New ST changes', 'Resolution', 'Interval change'], feedsCdrs: ['heart'] },
  { id: 'lp', name: 'Lumbar Puncture', category: 'procedures_poc', subcategory: 'neurologic', commonIndications: ['meningitis', 'SAH', 'headache'], unit: null, normalRange: null, quickFindings: ['Normal', 'Elevated WBC', 'Elevated protein', 'Xanthochromia', 'Elevated opening pressure'], feedsCdrs: [] },
  { id: 'paracentesis', name: 'Paracentesis', category: 'procedures_poc', subcategory: 'abdominal', commonIndications: ['ascites', 'SBP', 'abdominal distension'], unit: null, normalRange: null, quickFindings: ['Transudative', 'Exudative', 'SBP (elevated PMNs)', 'Bloody'], feedsCdrs: [] },
  { id: 'thoracentesis', name: 'Thoracentesis', category: 'procedures_poc', subcategory: 'pulmonary', commonIndications: ['pleural effusion', 'dyspnea', 'empyema'], unit: null, normalRange: null, quickFindings: ['Transudative', 'Exudative', 'Empyema', 'Bloody'], feedsCdrs: [] },
  { id: 'incision_drainage', name: 'Incision & Drainage', category: 'procedures_poc', subcategory: 'wound', commonIndications: ['abscess', 'wound infection'], unit: null, normalRange: null, quickFindings: ['Simple abscess', 'Complex abscess', 'Wound packing'], feedsCdrs: [] },
  { id: 'bedside_us', name: 'Bedside Ultrasound', category: 'procedures_poc', subcategory: 'point_of_care', commonIndications: ['procedural guidance', 'rapid assessment'], unit: null, normalRange: null, quickFindings: null, feedsCdrs: [] },
  { id: 'splint_cast', name: 'Splint/Cast', category: 'procedures_poc', subcategory: 'orthopedic', commonIndications: ['fracture', 'sprain', 'immobilization'], unit: null, normalRange: null, quickFindings: ['Splint applied', 'Cast applied', 'Reduction performed'], feedsCdrs: [] },
  { id: 'istat', name: 'iSTAT (POC Blood Gas)', category: 'procedures_poc', subcategory: 'point_of_care', commonIndications: ['acid-base', 'electrolytes', 'respiratory'], unit: null, normalRange: null, quickFindings: null, feedsCdrs: [] },
  { id: 'rapid_strep', name: 'Rapid Strep', category: 'procedures_poc', subcategory: 'point_of_care', commonIndications: ['sore throat', 'pharyngitis'], unit: null, normalRange: null, quickFindings: ['Positive', 'Negative'], feedsCdrs: ['centor_mcisaac'] },
  { id: 'rapid_flu', name: 'Rapid Influenza', category: 'procedures_poc', subcategory: 'point_of_care', commonIndications: ['fever', 'myalgia', 'respiratory illness'], unit: null, normalRange: null, quickFindings: ['Positive Flu A', 'Positive Flu B', 'Negative'], feedsCdrs: [] },
  { id: 'covid_rapid', name: 'COVID Rapid Test', category: 'procedures_poc', subcategory: 'point_of_care', commonIndications: ['respiratory illness', 'fever', 'exposure'], unit: null, normalRange: null, quickFindings: ['Positive', 'Negative'], feedsCdrs: [] },
  { id: 'poc_glucose', name: 'POC Glucose', category: 'procedures_poc', subcategory: 'point_of_care', commonIndications: ['altered mental status', 'diabetes', 'DKA', 'hypoglycemia'], unit: 'mg/dL', normalRange: '70-140', quickFindings: ['Normal', 'Hypoglycemia', 'Hyperglycemia', 'Critical high'], feedsCdrs: [] },
  { id: 'joint_aspiration', name: 'Arthrocentesis', category: 'procedures_poc', subcategory: 'orthopedic', commonIndications: ['septic joint', 'gout', 'effusion', 'joint pain'], unit: null, normalRange: null, quickFindings: ['Clear', 'Turbid/purulent', 'Bloody', 'Crystal positive'], feedsCdrs: [] },
  { id: 'rsv_rapid', name: 'RSV Rapid Test', category: 'procedures_poc', subcategory: 'point_of_care', commonIndications: ['respiratory illness', 'pediatric', 'bronchiolitis', 'wheezing'], unit: null, normalRange: null, quickFindings: ['Positive', 'Negative'], feedsCdrs: [] },

  // New airway procedures
  { id: 'intubation', name: 'Endotracheal Intubation', category: 'procedures_poc', subcategory: 'airway', commonIndications: ['respiratory failure', 'airway protection', 'altered mental status', 'status epilepticus'], unit: null, normalRange: null, quickFindings: ['RSI performed', 'Direct laryngoscopy', 'Video laryngoscopy', 'Bougie-assisted', 'First-pass success'], feedsCdrs: [] },
  { id: 'cricothyrotomy', name: 'Cricothyrotomy', category: 'procedures_poc', subcategory: 'airway', commonIndications: ['failed intubation', 'cannot intubate/cannot oxygenate', 'facial trauma', 'angioedema'], unit: null, normalRange: null, quickFindings: ['Surgical cric performed', 'Needle cric performed', 'Successful ventilation'], feedsCdrs: [] },
  { id: 'bvm_ventilation', name: 'BVM/Bag-Valve-Mask', category: 'procedures_poc', subcategory: 'airway', commonIndications: ['apnea', 'respiratory failure', 'pre-oxygenation', 'cardiac arrest'], unit: null, normalRange: null, quickFindings: ['Effective ventilation', 'Difficult ventilation', 'Two-person technique required'], feedsCdrs: [] },
  { id: 'bipap_cpap', name: 'BiPAP/CPAP (NIPPV)', category: 'procedures_poc', subcategory: 'airway', commonIndications: ['COPD exacerbation', 'CHF/pulmonary edema', 'respiratory distress', 'obstructive sleep apnea'], unit: null, normalRange: null, quickFindings: ['Improved respiratory status', 'Failed NIPPV', 'Intubation avoided'], feedsCdrs: [] },
  { id: 'supraglottic_airway', name: 'Supraglottic Airway (LMA/King)', category: 'procedures_poc', subcategory: 'airway', commonIndications: ['rescue airway', 'failed intubation', 'cardiac arrest', 'short procedure'], unit: null, normalRange: null, quickFindings: ['LMA placed', 'King tube placed', 'Adequate ventilation', 'Upgraded to ETT'], feedsCdrs: [] },
  { id: 'high_flow_nc', name: 'High-Flow Nasal Cannula', category: 'procedures_poc', subcategory: 'airway', commonIndications: ['hypoxia', 'respiratory distress', 'pre-oxygenation', 'post-extubation'], unit: null, normalRange: null, quickFindings: ['Improved oxygenation', 'FiO2 and flow rate set', 'Weaning initiated', 'Escalated to NIPPV'], feedsCdrs: [] },
  { id: 'mechanical_ventilation', name: 'Mechanical Ventilation Management', category: 'procedures_poc', subcategory: 'airway', commonIndications: ['respiratory failure', 'post-intubation', 'ARDS', 'status asthmaticus'], unit: null, normalRange: null, quickFindings: ['AC mode initiated', 'SIMV mode', 'Pressure support', 'Lung-protective settings (6 mL/kg IBW)', 'Settings adjusted'], feedsCdrs: [] },
  { id: 'nebulizer_treatment', name: 'Nebulizer Treatment', category: 'procedures_poc', subcategory: 'airway', commonIndications: ['asthma exacerbation', 'COPD exacerbation', 'bronchospasm', 'croup'], unit: null, normalRange: null, quickFindings: ['Albuterol given', 'Albuterol + ipratropium', 'Racemic epinephrine (croup)', 'Improved air movement', 'Repeat treatment needed'], feedsCdrs: [] },
  { id: 'airway_fb_removal', name: 'Airway Foreign Body Removal', category: 'procedures_poc', subcategory: 'airway', commonIndications: ['choking', 'airway foreign body', 'stridor', 'unable to ventilate', 'pediatric aspiration'], unit: null, normalRange: null, quickFindings: ['Magill forceps removal', 'Back blows/chest thrusts (infant)', 'Abdominal thrusts (Heimlich)', 'Removed by direct laryngoscopy', 'Required surgical airway'], feedsCdrs: [] },

  // New vascular access procedures
  { id: 'central_line', name: 'Central Line Placement', category: 'procedures_poc', subcategory: 'vascular_access', commonIndications: ['vasopressor administration', 'difficult IV access', 'CVP monitoring', 'rapid fluid resuscitation'], unit: null, normalRange: null, quickFindings: ['IJ placed', 'Subclavian placed', 'Femoral placed', 'US-guided', 'Confirmed by CXR'], feedsCdrs: [] },
  { id: 'arterial_line', name: 'Arterial Line', category: 'procedures_poc', subcategory: 'vascular_access', commonIndications: ['continuous BP monitoring', 'hemodynamic instability', 'frequent ABG sampling', 'vasopressor titration'], unit: null, normalRange: null, quickFindings: ['Radial placed', 'Femoral placed', 'Brachial placed', 'US-guided'], feedsCdrs: [] },
  { id: 'io_access', name: 'Intraosseous Access', category: 'procedures_poc', subcategory: 'vascular_access', commonIndications: ['cardiac arrest', 'failed IV access', 'pediatric emergency', 'critical access needed'], unit: null, normalRange: null, quickFindings: ['Tibial IO placed', 'Humeral IO placed', 'Sternal IO placed', 'Good flow confirmed'], feedsCdrs: [] },

  // New cardiac procedures
  { id: 'cardioversion', name: 'Cardioversion/Defibrillation', category: 'procedures_poc', subcategory: 'cardiac', commonIndications: ['unstable tachycardia', 'atrial fibrillation', 'SVT', 'ventricular fibrillation', 'VT with pulse'], unit: null, normalRange: null, quickFindings: ['Synchronized cardioversion', 'Defibrillation', 'Return to sinus', 'Required repeat shock'], feedsCdrs: [] },
  { id: 'transcutaneous_pacing', name: 'Transcutaneous Pacing', category: 'procedures_poc', subcategory: 'cardiac', commonIndications: ['symptomatic bradycardia', 'heart block', 'asystole', 'pacemaker failure'], unit: null, normalRange: null, quickFindings: ['Capture achieved', 'Failed capture', 'Rate set at ___ bpm'], feedsCdrs: [] },
  { id: 'pericardiocentesis', name: 'Pericardiocentesis', category: 'procedures_poc', subcategory: 'cardiac', commonIndications: ['cardiac tamponade', 'pericardial effusion', 'PEA arrest', 'Beck triad'], unit: null, normalRange: null, quickFindings: ['Bloody aspirate', 'Serous aspirate', 'Hemodynamic improvement', 'Drain placed'], feedsCdrs: [] },
  { id: 'resuscitative_thoracotomy', name: 'Resuscitative Thoracotomy', category: 'procedures_poc', subcategory: 'cardiac', commonIndications: ['penetrating thoracic trauma with arrest', 'witnessed arrest after penetrating trauma', 'cardiac tamponade'], unit: null, normalRange: null, quickFindings: ['Performed', 'Tamponade relieved', 'Aortic cross-clamp applied', 'ROSC achieved', 'No cardiac activity'], feedsCdrs: [] },
  { id: 'transvenous_pacemaker', name: 'Transvenous Pacemaker', category: 'procedures_poc', subcategory: 'cardiac', commonIndications: ['symptomatic bradycardia refractory to transcutaneous pacing', 'complete heart block', 'pacemaker malfunction', 'overdrive pacing'], unit: null, normalRange: null, quickFindings: ['Capture achieved', 'Wire positioned in RV', 'Rate and output set', 'Confirmed by CXR'], feedsCdrs: [] },

  // New pulmonary procedures
  { id: 'chest_tube', name: 'Chest Tube (Tube Thoracostomy)', category: 'procedures_poc', subcategory: 'pulmonary', commonIndications: ['pneumothorax', 'hemothorax', 'empyema', 'traumatic hemopneumothorax'], unit: null, normalRange: null, quickFindings: ['Air evacuated', 'Blood evacuated', 'Lung re-expanded', 'Continuous air leak', 'Output ___ mL'], feedsCdrs: [] },
  { id: 'needle_decompression', name: 'Needle Decompression', category: 'procedures_poc', subcategory: 'pulmonary', commonIndications: ['tension pneumothorax', 'traumatic arrest', 'sudden decompensation'], unit: null, normalRange: null, quickFindings: ['Rush of air', 'Hemodynamic improvement', 'Followed by chest tube'], feedsCdrs: [] },

  // New neurologic procedures
  { id: 'dix_hallpike_epley', name: 'Dix-Hallpike/Epley Maneuver', category: 'procedures_poc', subcategory: 'neurologic', commonIndications: ['vertigo', 'BPPV', 'dizziness', 'positional nystagmus'], unit: null, normalRange: null, quickFindings: ['Positive Dix-Hallpike (upbeat torsional nystagmus)', 'Negative Dix-Hallpike', 'Epley performed - symptoms resolved', 'Epley performed - persistent symptoms'], feedsCdrs: [] },
  { id: 'cranial_burr_hole', name: 'Emergency Cranial Burr Hole', category: 'procedures_poc', subcategory: 'neurologic', commonIndications: ['epidural hematoma with herniation', 'no neurosurgery available', 'uncal herniation', 'fixed dilated pupil'], unit: null, normalRange: null, quickFindings: ['Hematoma evacuated', 'Clinical improvement', 'Awaiting neurosurgical transfer'], feedsCdrs: [] },

  // New wound procedures
  { id: 'laceration_repair', name: 'Laceration Repair', category: 'procedures_poc', subcategory: 'wound', commonIndications: ['laceration', 'wound closure', 'traumatic wound', 'facial laceration'], unit: null, normalRange: null, quickFindings: ['Simple suture repair', 'Layered closure', 'Staples', 'Dermabond/tissue adhesive', 'Steri-strips'], feedsCdrs: [] },
  { id: 'wound_care', name: 'Wound Irrigation/Debridement', category: 'procedures_poc', subcategory: 'wound', commonIndications: ['contaminated wound', 'bite wound', 'crush injury', 'abrasion'], unit: null, normalRange: null, quickFindings: ['Irrigated and dressed', 'Debridement performed', 'Foreign body removed'], feedsCdrs: [] },
  { id: 'foreign_body_removal', name: 'Foreign Body Removal', category: 'procedures_poc', subcategory: 'wound', commonIndications: ['embedded foreign body', 'splinter', 'glass', 'metal fragment'], unit: null, normalRange: null, quickFindings: ['Foreign body removed', 'Partially removed', 'Retained foreign body'], feedsCdrs: [] },
  { id: 'nail_trephination', name: 'Nail Trephination', category: 'procedures_poc', subcategory: 'wound', commonIndications: ['subungual hematoma', 'nail bed injury', 'finger crush injury'], unit: null, normalRange: null, quickFindings: ['Hematoma drained', 'Pain relief achieved', 'Nail bed intact'], feedsCdrs: [] },
  { id: 'abscess_packing', name: 'Abscess Repacking', category: 'procedures_poc', subcategory: 'wound', commonIndications: ['abscess follow-up', 'wound packing change', 'healing assessment'], unit: null, normalRange: null, quickFindings: ['Repacked', 'Healing well', 'Persistent drainage', 'Cavity closing'], feedsCdrs: [] },
  { id: 'burn_care', name: 'Burn Wound Care', category: 'procedures_poc', subcategory: 'wound', commonIndications: ['thermal burn', 'chemical burn', 'electrical burn', 'scald burn'], unit: null, normalRange: null, quickFindings: ['Superficial (1st degree)', 'Partial thickness (2nd degree)', 'Full thickness (3rd degree)', 'Debrided and dressed'], feedsCdrs: [] },
  { id: 'ingrown_toenail', name: 'Ingrown Toenail/Partial Nail Avulsion', category: 'procedures_poc', subcategory: 'wound', commonIndications: ['ingrown toenail', 'paronychia', 'infected nail border'], unit: null, normalRange: null, quickFindings: ['Partial nail avulsion', 'Complete nail removal', 'Digital block performed', 'Phenol matrixectomy'], feedsCdrs: [] },
  { id: 'fishhook_removal', name: 'Fishhook Removal', category: 'procedures_poc', subcategory: 'wound', commonIndications: ['embedded fishhook', 'puncture wound', 'retained foreign body'], unit: null, normalRange: null, quickFindings: ['Retrograde technique', 'Advance and cut', 'String-yank technique', 'Needle cover technique'], feedsCdrs: [] },
  { id: 'ring_removal', name: 'Ring Removal', category: 'procedures_poc', subcategory: 'wound', commonIndications: ['finger swelling', 'ring constriction', 'vascular compromise'], unit: null, normalRange: null, quickFindings: ['String wrap technique', 'Ring cutter used', 'Lubrication/elevation', 'Intact ring removed'], feedsCdrs: [] },
  { id: 'nail_bed_repair', name: 'Nail Bed Repair', category: 'procedures_poc', subcategory: 'wound', commonIndications: ['nail bed laceration', 'finger crush', 'nail avulsion with laceration', 'tuft fracture'], unit: null, normalRange: null, quickFindings: ['Nail removed and bed repaired', 'Absorbable sutures placed', 'Nail replaced as splint', 'Digital block performed'], feedsCdrs: [] },
  { id: 'escharotomy', name: 'Escharotomy', category: 'procedures_poc', subcategory: 'wound', commonIndications: ['circumferential burn', 'compartment syndrome from burn', 'vascular compromise'], unit: null, normalRange: null, quickFindings: ['Performed on extremity', 'Performed on chest', 'Improved perfusion', 'Improved ventilation'], feedsCdrs: [] },
  { id: 'wound_exploration', name: 'Wound Exploration', category: 'procedures_poc', subcategory: 'wound', commonIndications: ['deep laceration', 'tendon injury evaluation', 'nerve injury evaluation', 'foreign body concern', 'hand laceration'], unit: null, normalRange: null, quickFindings: ['Tendon intact', 'Partial tendon laceration', 'Complete tendon laceration', 'Nerve intact', 'Foreign body found', 'No deep structure injury'], feedsCdrs: [] },

  // New orthopedic procedures
  { id: 'fracture_reduction', name: 'Fracture/Dislocation Reduction', category: 'procedures_poc', subcategory: 'orthopedic', commonIndications: ['displaced fracture', 'joint dislocation', 'deformity', 'neurovascular compromise'], unit: null, normalRange: null, quickFindings: ['Successful reduction', 'Post-reduction films adequate', 'Neurovascular intact post-reduction', 'Failed closed reduction'], feedsCdrs: [] },
  { id: 'procedural_sedation', name: 'Procedural Sedation', category: 'procedures_poc', subcategory: 'orthopedic', commonIndications: ['fracture reduction', 'dislocation reduction', 'abscess drainage', 'cardioversion'], unit: null, normalRange: null, quickFindings: ['Ketamine used', 'Propofol used', 'Etomidate used', 'Adequate sedation achieved', 'No complications'], feedsCdrs: [] },
  { id: 'shoulder_reduction', name: 'Shoulder Dislocation Reduction', category: 'procedures_poc', subcategory: 'orthopedic', commonIndications: ['anterior shoulder dislocation', 'posterior shoulder dislocation', 'recurrent dislocation'], unit: null, normalRange: null, quickFindings: ['External rotation technique', 'Cunningham technique', 'Traction-countertraction', 'Stimson technique', 'Post-reduction films confirmed'], feedsCdrs: [] },
  { id: 'compartment_pressure', name: 'Compartment Pressure Measurement', category: 'procedures_poc', subcategory: 'orthopedic', commonIndications: ['compartment syndrome', 'crush injury', 'fracture with severe pain', 'tight cast/splint'], unit: 'mmHg', normalRange: '<20', quickFindings: ['Normal pressure', 'Elevated (>30 mmHg)', 'Delta pressure <30 (surgical)'], feedsCdrs: [] },
  { id: 'traction_splint', name: 'Traction Splint', category: 'procedures_poc', subcategory: 'orthopedic', commonIndications: ['femur fracture', 'mid-shaft femur', 'pre-hospital stabilization'], unit: null, normalRange: null, quickFindings: ['Hare traction applied', 'Thomas splint applied', 'Neurovascular intact post-application'], feedsCdrs: [] },
  { id: 'pelvic_binder', name: 'Pelvic Binder Application', category: 'procedures_poc', subcategory: 'orthopedic', commonIndications: ['pelvic fracture', 'open-book pelvis', 'hemodynamic instability with pelvic trauma'], unit: null, normalRange: null, quickFindings: ['Binder applied at greater trochanters', 'Hemodynamic improvement', 'Maintained pending OR'], feedsCdrs: [] },
  { id: 'nursemaids_elbow', name: "Nursemaid's Elbow Reduction", category: 'procedures_poc', subcategory: 'orthopedic', commonIndications: ['radial head subluxation', 'pediatric arm not moving', 'mechanism of pulling on arm', 'toddler elbow injury'], unit: null, normalRange: null, quickFindings: ['Hyperpronation technique - successful', 'Supination/flexion technique - successful', 'Palpable click', 'Child using arm post-reduction'], feedsCdrs: [] },
  { id: 'ganglion_aspiration', name: 'Ganglion Cyst Aspiration', category: 'procedures_poc', subcategory: 'orthopedic', commonIndications: ['ganglion cyst', 'wrist mass', 'hand mass', 'dorsal wrist swelling'], unit: null, normalRange: null, quickFindings: ['Aspirated clear gelatinous fluid', 'Steroid injected', 'Cyst decompressed', 'Recurrence counseling given'], feedsCdrs: [] },

  // New GI procedures
  { id: 'ng_og_tube', name: 'NG/OG Tube Placement', category: 'procedures_poc', subcategory: 'gastrointestinal', commonIndications: ['GI bleed', 'bowel obstruction', 'gastric decompression', 'medication administration', 'overdose'], unit: null, normalRange: null, quickFindings: ['Placed and confirmed', 'Bloody aspirate', 'Bilious aspirate', 'Decompression achieved'], feedsCdrs: [] },
  { id: 'rectal_exam', name: 'Digital Rectal Exam', category: 'procedures_poc', subcategory: 'gastrointestinal', commonIndications: ['GI bleed', 'rectal bleeding', 'prostate evaluation', 'rectal foreign body', 'saddle anesthesia'], unit: null, normalRange: null, quickFindings: ['Normal', 'Guaiac positive', 'Guaiac negative', 'Gross blood', 'Mass palpated', 'Normal tone'], feedsCdrs: [] },
  { id: 'rectal_fb_removal', name: 'Rectal Foreign Body Removal', category: 'procedures_poc', subcategory: 'gastrointestinal', commonIndications: ['retained rectal foreign body', 'abdominal pain', 'rectal pain'], unit: null, normalRange: null, quickFindings: ['Removed bedside', 'Removed with sedation', 'Required surgical consultation', 'Post-removal imaging normal'], feedsCdrs: [] },
  { id: 'hernia_reduction', name: 'Hernia Reduction', category: 'procedures_poc', subcategory: 'gastrointestinal', commonIndications: ['incarcerated inguinal hernia', 'incarcerated umbilical hernia', 'groin pain with bulge'], unit: null, normalRange: null, quickFindings: ['Successful manual reduction', 'Failed reduction (surgical consult)', 'Trendelenburg with sedation'], feedsCdrs: [] },
  { id: 'rectal_prolapse_reduction', name: 'Rectal Prolapse Reduction', category: 'procedures_poc', subcategory: 'gastrointestinal', commonIndications: ['rectal prolapse', 'rectal protrusion', 'elderly patient with prolapse'], unit: null, normalRange: null, quickFindings: ['Manual reduction successful', 'Sugar granule technique', 'Failed reduction (surgical consult)'], feedsCdrs: [] },
  { id: 'hemorrhoid_thrombectomy', name: 'Thrombosed Hemorrhoid Excision', category: 'procedures_poc', subcategory: 'gastrointestinal', commonIndications: ['thrombosed external hemorrhoid', 'acute perianal pain', 'perianal mass'], unit: null, normalRange: null, quickFindings: ['Elliptical excision', 'Clot evacuated', 'Local anesthesia used', 'Pain relief achieved'], feedsCdrs: [] },

  // New GU procedures
  { id: 'foley_catheter', name: 'Foley Catheter', category: 'procedures_poc', subcategory: 'genitourinary', commonIndications: ['urinary retention', 'urine output monitoring', 'hemodynamic instability', 'trauma'], unit: null, normalRange: null, quickFindings: ['Placed without difficulty', 'Difficult placement', 'Gross hematuria', 'Large residual'], feedsCdrs: [] },
  { id: 'paraphimosis_reduction', name: 'Paraphimosis Reduction', category: 'procedures_poc', subcategory: 'genitourinary', commonIndications: ['paraphimosis', 'foreskin entrapment', 'penile swelling'], unit: null, normalRange: null, quickFindings: ['Manual reduction successful', 'Ice/compression then reduction', 'Dorsal slit required', 'Urology consulted'], feedsCdrs: [] },
  { id: 'priapism_management', name: 'Priapism Management', category: 'procedures_poc', subcategory: 'genitourinary', commonIndications: ['priapism', 'ischemic priapism', 'sickle cell crisis', 'prolonged erection'], unit: null, normalRange: null, quickFindings: ['Aspiration performed', 'Phenylephrine injection', 'Detumescence achieved', 'Urology consulted'], feedsCdrs: [] },

  // New ENT procedures
  { id: 'epistaxis_management', name: 'Epistaxis Management', category: 'procedures_poc', subcategory: 'ent', commonIndications: ['nosebleed', 'anterior epistaxis', 'posterior epistaxis', 'anticoagulated patient'], unit: null, normalRange: null, quickFindings: ['Direct pressure controlled', 'Cautery performed', 'Anterior packing placed', 'Posterior packing placed', 'Rhino Rocket placed'], feedsCdrs: [] },
  { id: 'peritonsillar_drainage', name: 'Peritonsillar Abscess Drainage', category: 'procedures_poc', subcategory: 'ent', commonIndications: ['peritonsillar abscess', 'trismus', 'odynophagia', 'uvular deviation'], unit: null, normalRange: null, quickFindings: ['Aspirated purulent fluid', 'I&D performed', 'Needle aspiration', 'No abscess on aspiration'], feedsCdrs: [] },
  { id: 'ear_irrigation', name: 'Ear Irrigation/FB Removal', category: 'procedures_poc', subcategory: 'ent', commonIndications: ['cerumen impaction', 'ear foreign body', 'hearing loss', 'otalgia'], unit: null, normalRange: null, quickFindings: ['Cerumen removed', 'Foreign body removed', 'TM visualized and intact', 'TM perforation noted'], feedsCdrs: [] },
  { id: 'nasal_fb_removal', name: 'Nasal Foreign Body Removal', category: 'procedures_poc', subcategory: 'ent', commonIndications: ['nasal foreign body', 'pediatric FB', 'nasal obstruction'], unit: null, normalRange: null, quickFindings: ['FB removed', "Parent's kiss technique", 'Alligator forceps', 'Balloon catheter extraction'], feedsCdrs: [] },
  { id: 'auricular_hematoma_id', name: 'Auricular Hematoma I&D', category: 'procedures_poc', subcategory: 'ent', commonIndications: ['auricular hematoma', 'ear trauma', 'cauliflower ear prevention'], unit: null, normalRange: null, quickFindings: ['Hematoma drained', 'Bolster dressing applied', 'Compression dressing placed'], feedsCdrs: [] },

  // New ophthalmologic procedures
  { id: 'slit_lamp', name: 'Slit Lamp Exam', category: 'procedures_poc', subcategory: 'ophthalmologic', commonIndications: ['eye pain', 'red eye', 'foreign body sensation', 'vision change', 'chemical exposure'], unit: null, normalRange: null, quickFindings: ['Normal', 'Corneal abrasion', 'Corneal ulcer', 'Foreign body', 'Hyphema', 'Cell/flare (iritis)'], feedsCdrs: [] },
  { id: 'lateral_canthotomy', name: 'Lateral Canthotomy', category: 'procedures_poc', subcategory: 'ophthalmologic', commonIndications: ['orbital compartment syndrome', 'retrobulbar hemorrhage', 'proptosis with vision loss'], unit: null, normalRange: null, quickFindings: ['Canthotomy and cantholysis performed', 'IOP decreased', 'Vision improved'], feedsCdrs: [] },
  { id: 'eye_foreign_body', name: 'Eye Foreign Body Removal', category: 'procedures_poc', subcategory: 'ophthalmologic', commonIndications: ['corneal foreign body', 'metallic FB', 'rust ring', 'eye pain after grinding'], unit: null, normalRange: null, quickFindings: ['FB removed with needle/burr', 'Rust ring removed', 'Seidel test negative', 'Fluorescein uptake resolved'], feedsCdrs: [] },
  { id: 'ocular_irrigation', name: 'Ocular/Eye Irrigation', category: 'procedures_poc', subcategory: 'ophthalmologic', commonIndications: ['chemical exposure to eye', 'alkali burn', 'acid burn', 'foreign body in eye'], unit: null, normalRange: null, quickFindings: ['pH normalized (7.0-7.4)', 'Irrigation with 1L NS', 'Irrigation with 2L NS', 'Slit lamp post-irrigation normal'], feedsCdrs: [] },
  { id: 'tonometry', name: 'Tonometry (IOP Measurement)', category: 'procedures_poc', subcategory: 'ophthalmologic', commonIndications: ['acute glaucoma', 'eye pain', 'blurred vision', 'red eye', 'post-lateral canthotomy'], unit: 'mmHg', normalRange: '10-21', quickFindings: ['Normal IOP', 'Elevated IOP (>21 mmHg)', 'Critically elevated (>40 mmHg)', 'IOP decreased post-treatment'], feedsCdrs: [] },
  { id: 'fundoscopic_exam', name: 'Fundoscopic Exam', category: 'procedures_poc', subcategory: 'ophthalmologic', commonIndications: ['headache', 'papilledema evaluation', 'vision loss', 'hypertensive emergency', 'increased ICP'], unit: null, normalRange: null, quickFindings: ['Normal', 'Papilledema', 'Retinal hemorrhages', 'Cotton-wool spots', 'Disc pallor', 'CRVO/CRAO pattern'], feedsCdrs: [] },

  // New anesthesia procedures
  { id: 'nerve_block', name: 'Nerve Block/Regional Anesthesia', category: 'procedures_poc', subcategory: 'anesthesia', commonIndications: ['laceration repair', 'fracture pain', 'abscess drainage', 'hip fracture', 'rib fractures'], unit: null, normalRange: null, quickFindings: ['Digital block', 'Femoral nerve block', 'Fascia iliaca block', 'Hematoma block', 'Intercostal block', 'US-guided'], feedsCdrs: [] },
  { id: 'local_anesthesia', name: 'Local Anesthesia', category: 'procedures_poc', subcategory: 'anesthesia', commonIndications: ['wound repair', 'abscess drainage', 'procedural anesthesia'], unit: null, normalRange: null, quickFindings: ['Lidocaine 1%', 'Lidocaine with epinephrine', 'Bupivacaine', 'Buffered lidocaine'], feedsCdrs: [] },
  { id: 'sphenopalatine_block', name: 'Sphenopalatine Ganglion Block', category: 'procedures_poc', subcategory: 'anesthesia', commonIndications: ['migraine', 'cluster headache', 'epistaxis', 'trigeminal neuralgia'], unit: null, normalRange: null, quickFindings: ['Performed with atomized lidocaine', 'Performed with cotton-tip applicator', 'Pain relief achieved', 'Partial relief'], feedsCdrs: [] },
  { id: 'trigger_point_injection', name: 'Trigger Point Injection', category: 'procedures_poc', subcategory: 'anesthesia', commonIndications: ['myofascial pain', 'muscle spasm', 'neck pain', 'back pain', 'tension headache'], unit: null, normalRange: null, quickFindings: ['Local anesthetic injected', 'Pain relief achieved', 'Twitch response elicited', 'Multiple trigger points treated'], feedsCdrs: [] },

  // New OB/GYN procedures
  { id: 'vaginal_delivery', name: 'Emergency Vaginal Delivery', category: 'procedures_poc', subcategory: 'obstetric', commonIndications: ['precipitous delivery', 'imminent delivery', 'crowning'], unit: null, normalRange: null, quickFindings: ['Spontaneous vaginal delivery', 'Nuchal cord reduced', 'Apgar _/_', 'Placenta delivered'], feedsCdrs: [] },
  { id: 'resuscitative_hysterotomy', name: 'Resuscitative Hysterotomy', category: 'procedures_poc', subcategory: 'obstetric', commonIndications: ['maternal cardiac arrest', 'perimortem cesarean', 'gravid uterus >20 weeks'], unit: null, normalRange: null, quickFindings: ['Performed', 'ROSC achieved', 'Infant delivered'], feedsCdrs: [] },
  { id: 'postpartum_hemorrhage', name: 'Postpartum Hemorrhage Management', category: 'procedures_poc', subcategory: 'obstetric', commonIndications: ['postpartum hemorrhage', 'uterine atony', 'retained placenta', 'vaginal delivery complications'], unit: null, normalRange: null, quickFindings: ['Uterine massage', 'Uterotonics administered', 'Intrauterine balloon placed', 'Manual placenta removal', 'OB consulted'], feedsCdrs: [] },
  { id: 'speculum_exam', name: 'Pelvic/Speculum Exam', category: 'procedures_poc', subcategory: 'gynecologic', commonIndications: ['vaginal bleeding', 'pelvic pain', 'vaginal discharge', 'threatened abortion', 'foreign body'], unit: null, normalRange: null, quickFindings: ['Normal', 'Cervical os open', 'Cervical os closed', 'Active bleeding', 'Foreign body removed', 'Cervical motion tenderness'], feedsCdrs: [] },
  { id: 'sexual_assault_exam', name: 'Sexual Assault Forensic Exam', category: 'procedures_poc', subcategory: 'gynecologic', commonIndications: ['sexual assault', 'forensic evidence collection', 'SANE exam'], unit: null, normalRange: null, quickFindings: ['Evidence kit collected', 'Prophylactic medications given', 'Counseling provided', 'Follow-up arranged'], feedsCdrs: [] },
  { id: 'bartholin_drainage', name: 'Bartholin Abscess Drainage', category: 'procedures_poc', subcategory: 'gynecologic', commonIndications: ['Bartholin abscess', 'Bartholin cyst', 'labial swelling', 'vulvar pain'], unit: null, normalRange: null, quickFindings: ['I&D performed', 'Word catheter placed', 'Marsupialization', 'Purulent drainage'], feedsCdrs: [] },

  // New dental procedures
  { id: 'dental_block', name: 'Dental Block/Tooth Stabilization', category: 'procedures_poc', subcategory: 'dental', commonIndications: ['dental pain', 'tooth fracture', 'avulsed tooth', 'dental abscess'], unit: null, normalRange: null, quickFindings: ['Inferior alveolar block', 'Mental nerve block', 'Infraorbital block', 'Tooth reimplanted', 'Calcium hydroxide placed'], feedsCdrs: [] },
  { id: 'tmj_reduction', name: 'TMJ Dislocation Reduction', category: 'procedures_poc', subcategory: 'dental', commonIndications: ['TMJ dislocation', 'inability to close mouth', 'jaw locked open'], unit: null, normalRange: null, quickFindings: ['Successful bilateral reduction', 'Successful unilateral reduction', 'Sedation required', 'Barton bandage applied'], feedsCdrs: [] },

  // New resuscitation procedures
  { id: 'cpr', name: 'CPR/Code Management', category: 'procedures_poc', subcategory: 'resuscitation', commonIndications: ['cardiac arrest', 'PEA', 'asystole', 'VFib', 'pulseless VT'], unit: null, normalRange: null, quickFindings: ['ROSC achieved', 'Asystole - pronounced', 'PEA - ongoing', 'Total arrest time ___'], feedsCdrs: [] },
  { id: 'rapid_infuser', name: 'Rapid Infuser/Massive Transfusion', category: 'procedures_poc', subcategory: 'resuscitation', commonIndications: ['hemorrhagic shock', 'massive transfusion protocol', 'GI bleed', 'trauma'], unit: null, normalRange: null, quickFindings: ['MTP activated', 'pRBC transfused ___ units', 'FFP given', 'Platelets given', 'Cryoprecipitate given'], feedsCdrs: [] },
  { id: 'push_dose_pressors', name: 'Push-Dose Pressors', category: 'procedures_poc', subcategory: 'resuscitation', commonIndications: ['peri-intubation hypotension', 'transient hypotension', 'bridge to vasopressor drip'], unit: null, normalRange: null, quickFindings: ['Phenylephrine push-dose', 'Epinephrine push-dose', 'Hemodynamic improvement'], feedsCdrs: [] },
  { id: 'targeted_temp_mgmt', name: 'Targeted Temperature Management', category: 'procedures_poc', subcategory: 'resuscitation', commonIndications: ['post-cardiac arrest', 'ROSC', 'neuroprotection'], unit: null, normalRange: null, quickFindings: ['Cooling initiated', 'Target temp achieved 33°C', 'Target temp achieved 36°C', 'Rewarming phase'], feedsCdrs: [] },
  { id: 'blood_warmer', name: 'Blood/Fluid Warmer', category: 'procedures_poc', subcategory: 'resuscitation', commonIndications: ['massive transfusion', 'hypothermia prevention', 'rapid fluid resuscitation'], unit: null, normalRange: null, quickFindings: ['Level 1 infuser used', 'Belmont rapid infuser', 'Warm fluids administered'], feedsCdrs: [] },
  { id: 'reboa', name: 'REBOA', category: 'procedures_poc', subcategory: 'resuscitation', commonIndications: ['non-compressible torso hemorrhage', 'traumatic arrest', 'hemorrhagic shock'], unit: null, normalRange: null, quickFindings: ['Zone 1 occlusion', 'Zone 3 occlusion', 'Hemodynamic improvement', 'Bridge to OR'], feedsCdrs: [] },
  { id: 'autotransfusion', name: 'Autotransfusion (Cell Saver)', category: 'procedures_poc', subcategory: 'resuscitation', commonIndications: ['massive hemothorax', 'autologous blood recovery', "Jehovah's Witness patient"], unit: null, normalRange: null, quickFindings: ['Collected and reinfused ___ mL', 'Successful autotransfusion'], feedsCdrs: [] },
  { id: 'vasopressor_infusion', name: 'Vasopressor/Inotrope Infusion', category: 'procedures_poc', subcategory: 'resuscitation', commonIndications: ['septic shock', 'cardiogenic shock', 'refractory hypotension', 'post-arrest'], unit: null, normalRange: null, quickFindings: ['Norepinephrine started', 'Vasopressin added', 'Epinephrine started', 'Dobutamine for inotropy', 'MAP >65 achieved'], feedsCdrs: ['sepsis'] },

  // New toxicology procedures
  { id: 'activated_charcoal', name: 'Activated Charcoal', category: 'procedures_poc', subcategory: 'toxicology', commonIndications: ['acute ingestion', 'overdose within 1-2 hours', 'decontamination'], unit: null, normalRange: null, quickFindings: ['Administered PO', 'Administered via NG', 'Tolerated well', 'Vomited'], feedsCdrs: [] },
  { id: 'whole_bowel_irrigation', name: 'Whole Bowel Irrigation', category: 'procedures_poc', subcategory: 'toxicology', commonIndications: ['sustained-release ingestion', 'iron overdose', 'body packing', 'lithium overdose'], unit: null, normalRange: null, quickFindings: ['GoLYTELY administered', 'Clear rectal effluent achieved', 'Ongoing irrigation'], feedsCdrs: [] },
  { id: 'skin_decontamination', name: 'Skin Decontamination', category: 'procedures_poc', subcategory: 'toxicology', commonIndications: ['chemical exposure', 'hazmat', 'organophosphate exposure', 'caustic exposure'], unit: null, normalRange: null, quickFindings: ['Full body decontamination', 'Partial decontamination', 'Copious water irrigation'], feedsCdrs: [] },

  // New environmental procedures
  { id: 'warming_measures', name: 'Active Warming Measures', category: 'procedures_poc', subcategory: 'environmental', commonIndications: ['hypothermia', 'cold exposure', 'submersion', 'environmental exposure'], unit: null, normalRange: null, quickFindings: ['Bair Hugger applied', 'Warm IV fluids', 'Warm blankets', 'Core temp improving'], feedsCdrs: [] },
  { id: 'cooling_measures', name: 'Active Cooling Measures', category: 'procedures_poc', subcategory: 'environmental', commonIndications: ['heat stroke', 'hyperthermia', 'malignant hyperthermia', 'NMS'], unit: null, normalRange: null, quickFindings: ['Ice bath immersion', 'Evaporative cooling', 'Cold IV fluids', 'Core temp decreasing'], feedsCdrs: [] },
  { id: 'tick_removal', name: 'Tick Removal', category: 'procedures_poc', subcategory: 'environmental', commonIndications: ['embedded tick', 'tick bite', 'Lyme disease concern'], unit: null, normalRange: null, quickFindings: ['Tick removed intact', 'Tick removed with mouthparts', 'Partial removal'], feedsCdrs: [] },

  // New monitoring procedures
  { id: 'capnography', name: 'End-Tidal CO2/Capnography', category: 'procedures_poc', subcategory: 'monitoring', commonIndications: ['ETT confirmation', 'CPR quality monitoring', 'sedation monitoring', 'respiratory status'], unit: 'mmHg', normalRange: '35-45', quickFindings: ['Normal waveform', 'Low EtCO2 (<10 during CPR)', 'Rising EtCO2 (ROSC)', 'Absent waveform (esophageal)'], feedsCdrs: [] },
  { id: 'peak_flow', name: 'Peak Flow Measurement', category: 'procedures_poc', subcategory: 'monitoring', commonIndications: ['asthma exacerbation', 'COPD exacerbation', 'dyspnea', 'wheezing'], unit: 'L/min', normalRange: null, quickFindings: ['>80% predicted (mild)', '50-80% predicted (moderate)', '<50% predicted (severe)', 'Improved post-treatment'], feedsCdrs: [] },
  { id: 'pulse_oximetry', name: 'Continuous Pulse Oximetry', category: 'procedures_poc', subcategory: 'monitoring', commonIndications: ['respiratory distress', 'sedation monitoring', 'hypoxia', 'carbon monoxide'], unit: '%', normalRange: '95-100', quickFindings: ['Normal >95%', 'Mild hypoxia 90-94%', 'Moderate hypoxia 85-89%', 'Severe hypoxia <85%'], feedsCdrs: [] },
  { id: 'cardiac_monitor', name: 'Continuous Cardiac Monitor', category: 'procedures_poc', subcategory: 'monitoring', commonIndications: ['chest pain', 'arrhythmia', 'syncope', 'electrolyte abnormality', 'overdose'], unit: null, normalRange: null, quickFindings: ['Normal sinus rhythm', 'Sinus tachycardia', 'Sinus bradycardia', 'Atrial fibrillation', 'PVCs', 'ST changes noted'], feedsCdrs: [] },
  { id: 'telemetry', name: 'Telemetry Monitoring', category: 'procedures_poc', subcategory: 'monitoring', commonIndications: ['arrhythmia monitoring', 'ACS observation', 'syncope workup', 'post-cardioversion'], unit: null, normalRange: null, quickFindings: ['No events', 'Intermittent PVCs', 'PACs noted', 'SVT episode captured', 'AF with RVR captured'], feedsCdrs: [] },
  { id: 'bladder_scan', name: 'Bladder Scan (PVR)', category: 'procedures_poc', subcategory: 'monitoring', commonIndications: ['urinary retention', 'post-void residual', 'difficulty voiding', 'neurogenic bladder'], unit: 'mL', normalRange: '<100', quickFindings: ['Normal PVR (<100 mL)', 'Elevated PVR (>200 mL)', 'Significant retention (>500 mL)'], feedsCdrs: [] },
  { id: 'blood_gas_interpretation', name: 'Blood Gas Interpretation', category: 'procedures_poc', subcategory: 'monitoring', commonIndications: ['acid-base disorder', 'respiratory failure', 'DKA', 'toxic ingestion', 'shock'], unit: null, normalRange: null, quickFindings: ['Respiratory acidosis', 'Respiratory alkalosis', 'Metabolic acidosis (AG)', 'Metabolic acidosis (non-AG)', 'Metabolic alkalosis', 'Mixed disorder'], feedsCdrs: [] },
]

// ---------------------------------------------------------------------------
// Seed function
// ---------------------------------------------------------------------------

async function seedTestLibrary(): Promise<void> {
  console.log(`Seeding ${tests.length} tests into testLibrary collection...`)

  const BATCH_SIZE = 500
  let written = 0

  for (let i = 0; i < tests.length; i += BATCH_SIZE) {
    const batch = db.batch()
    const chunk = tests.slice(i, i + BATCH_SIZE)

    for (const test of chunk) {
      const docRef = db.collection('testLibrary').doc(test.id)
      batch.set(docRef, test)
    }

    await batch.commit()
    written += chunk.length
    console.log(`Progress: ${written}/${tests.length}`)
  }

  console.log(`Done! Seeded ${written} tests into testLibrary collection.`)
}

seedTestLibrary().catch((err) => {
  console.error('Fatal error:', err)
  process.exit(1)
})
