name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Enable corepack and install dependencies
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate
          pnpm -C frontend install
      - name: Lint
        run: pnpm -C frontend lint
      - name: Typecheck
        run: pnpm -C frontend typecheck
      - name: Test
        run: pnpm -C frontend test
      - name: Build
        run: pnpm -C frontend build

